KronicDeth/intellij-elixir

intellij_elixir.xml, src/org/elixir_lang/intellij_elixir/Quoter.java
Resolves #106 
Convert from direct `send` to emulating `GenServer.call`.
=> Upgrade to intellj_elixir v1.0.0

idea.xml
14.0.2 is no longer available on http://download-cf.jetbrains/com/idea.
Block #167
=> Update IDEA from 14.0.2 to 14.1.4

.idea/libraries/junit_4_11.xml, .idea/runConfigurations/org_elixir_lang.xml, elixir.xml, intellij-elixir.iml, intellij-elixir.xml, module_intellij-elixir.xml, src/org/elixir_lang/intellij_elixir/Quoter.java, tests/org/elixir_lang/parser_definition/ElixirLangElixirParsingTestCase.java
=> Test parsing of elixir-lang/elixir

README.md
`http://http://elixir-lang.org/` -> `http://elixir-lang.org/`
=> fix link to elixir website

README.md
two screenshots can not be displayed.
=> fix links of screenshots

src/org/elixir_lang/sdk/ElixirSdkType.java
=> Default SDK path for Linux and Windows

src/org/elixir_lang/sdk/ElixirSdkType.java
=> more flexible version parsing

README.md
On Windows mx --version gives this result:
Elixir 1.1.0
So we need to check for "Elixir" in the first line of output.
=> Changes for Windows settings

src/org/elixir_lang/mix/runner/MixRunConfigurationBase.java
=> Fix 'Elixir Mix run configuration not persisting past restart'

src/org/elixir_lang/action/CreateElixirModuleAction.java
Fixes #214 
* Bug Fixes
* Check if a file exists before allowing Elixir Module to be created.  If it exists, show an error with the conflicting path.
=> Check if a file exists before allowing Elixir Module to be created

src/org/elixir_lang/annonator/ModuleAttribute.java
Fixes #269
* Enhancements
* Error reporting for type highlighter gives the Class, Excerpt and Full Text when an unknown element type is encountered as the Excerpt alone is not enough sometimes.
* Bug Fixes
* While typing, before `:` in keyword pairs, after the `when`, such as in `@spec foo(id) :: id when id` before finishing typing `@spec foo(id) :: id when id: String.t`, the keyword key will be properly highlighted as a Type Parameter.
=> Highlight type parameter when missing type

src/org/elixir_lang/reference/Callable.java
=> Check parent for isVariable(ElixirMapUpdateArguments)

src/org/elixir_lang/annonator/ModuleAttribute.java
Fixes #395
* In `@type unquote({name, nil, []}) :: foo`, `name` will be highlighted as a type parameter even though it is not strictly the name that will appear as a type parameter.
=> Highlight quoted form inside unquote for type parameters

src/org/elixir_lang/errorreport/Logger.java, src/org/elixir_lang/reference/Callable.java
Resolves #451
* Show element class in all error reports
=> Show element class in all error reports

CODE_OF_CONDUCT.md, LICENSE.md
* Add `LICENSE.md` for Apache 2.0 license
* Add `CODE_OF_CONDUCT.md`
=> Add missing root files

README.md
It's not possible to disable all error inspections, provide
link to Jetbrains issue to fix it.
=> Add details to README about using ruby for eex

.travis.yml
using approach from https://stackoverflow.com/a/22466509/25192
=> fix ci jdk download

src/org/elixir_lang/sdk/ElixirSdkType.java
=> Handle Elixir versions with non-numeric parts

src/org/elixir_lang/mix/importWizard/MixProjectRootStep.java
Fixes #604 
* `mix local.hex --force` before `mix deps.get` during project import to prevent prompt for hex update when local hex is earlier than that required by `mix`.
* Fix warnings and format `MixProjectRootStep`
=> `mix local.hex --force` before `mix deps.get`

src/org/elixir_lang/sdk/ElixirSdkType.java
Fixes #194
* Search for Elixir SDKs in `/nix/store` on Mac if homebrew path does not exist
=> SDK Paths on Nix

src/org/elixir_lang/psi/stub/call/Deserialized.java
Fixes #781 
* Increase suspect `nameSetSize` from `4` to `10` because a `Poison.Encoder` has an `impl` module for 4 types, and so has 4 canonical names.
* Only read-ahead if guard length is non-zero; otherwise, only warn the nameSetSize may be suspect and don't read-ahead as this can mess up OK namesets.
=> Increase suspect nameSetSize to 10

src/org/elixir_lang/sdk/ElixirSdkType.java
Resolves #762
* Merge both homebrew and nix store on Mac
* Merge default and nix store on Linux
=> Check more locations in homePathByVersion

src/org/elixir_lang/beam/Beam.java, src/org/elixir_lang/beam/chunk/Chunk.java, src/org/elixir_lang/beam/psi/BeamFileImpl.java, tests/org/elixir_lang/beam/BeamTest.java
Fixes #791 
* Include `VirtualFile` path in Beam read errors
=> Include VirtualFile path in Beam read errors

src/org/elixir_lang/debugger/xdebug/ElixirXDebugProcess.java, src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
Resolves #315
* Convert ANSI escape codes to colored output in `mix` Run and Debug output
=> Convert ANSI escape codes to colored output

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
Fixes #978
* Run `Qualified#moduleName` `getText` in Read Action.
=> Run Qualified#moduleName getText in Read Action

src/org/elixir_lang/credo/Annotator.java
Fixes #984
* Scratch Files have a `Project`, but not a `Module`, so change flow to use `Project` when `Module` is `null` in credo annotator.
=> Use Project instead of Module for Scratch Files in credo annotator

src/org/elixir_lang/file/LevelPropertyPusher.java
Fixes #992
* Don't use `StreamEx` because support is inconsistent across IDEs
=> Don't use StreamEx because support is inconsistent across IDEs

src/org/elixir_lang/beam/Beam.kt
Fixes #1058
Fixes #1011 
Fixes #952
Fixes #838
* Log available bytes and total size when header is not FOR1
=> Log available bytes and total size when header is not FOR1

src/org/elixir_lang/TypedHandler.java
Resolves #497 
* Complete `#{` with `}`.
=> Complete #{ with }

.travis.yml, RELEASING.md, build.gradle, gradle.properties, src/org/elixir_lang/eex/file/ElementType.java
* Update IntelliJ versions in build matrix to include `2018.1` and latest patch version of other versions.
=> Update IntelliJ versions in build matrix

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/reference/Callable.kt
Fixes #1144 
* Treat EEx tag the same as StabBody for use scope.
=> Treat EEx tag the same as StabBody for use scope

src/org/elixir_lang/facet/sdks/Configurable.kt
Fixes #1267
Fixes #1278
* Wrap `LibraryTable#removeLibrary` in write action.
* Wrap `Library#modifiableModule#commit` in write action.
=> Wrap LibraryTable and Library writes in write action

src/org/elixir_lang/mix/Dep.kt
* Handle `commit` and `override` for `Mix.Dep`.
=> Handle commit and overrride for Mix.Dep

src/org/elixir_lang/mix/Watcher.kt
Fixes #1281
* Check if `Mix.Dep` has already been seen to prevent recursive loops.
=> Check if Mix.Dep has already been seen to prevent recursive loops

README.md
I prefer this transliteration, even though it's not the one I have on my docs.
Once again, thanks for the awesome project!
=> Fix my last name in the list of donors

CHANGELOG.md, README.md, gradle.properties, resources/META-INF/changelog.html
* Fix image links in `README`.
=> Fix image links

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/mix/Dep.kt
* Ignore tag when finding path to dep.
=> Ignore tag when finding path to dep

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/psi/impl/PsiElementImpl.kt
Fixes #1430
* Get view provider document in read action
=> Get view provider document in read action

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/rebar3/DepGatherer.kt
Fixes #1425
* Support `rebar.config` deps that are name only.
=> Support rebar.config deps that are name only

resources/liveTemplates/Elixir.xml
added template for generating `describe` ExUnit block.
=> added ExUnit describe block template

README.md, RELEASING.md, resources/META-INF/description.html
* Update donor list
* Merge all donation streams together
* Emphasize that GitHub Sponsors is the best pick because of zero fees currently.
=> Update Donor Lists

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/reference/resolver/Callable.kt
Fixes #2006
* Check if `project` is not dumb in `nameArityInAnyModule`.
=> Check if project is not dumb in nameArityInAnyModule

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/psi/impl/ProcessDeclarationsImpl.kt
Fixes #2577
* Ignore tuples as type restrictions that occur during typing
=> Ignore tuples as type restrictions that occur during typing

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/documentation/BeamDocsHelper.kt
Fixes #2593
* Log unknown element for fetching docs from BEAM file
=> Log unknown element for fetching docs from BEAM file

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/facet/configurable/Project.kt
Fixes #2702
* Add the facet in a write action in addition to setting the SDK.
=> Add the facet in a write action in addition to setting the SDK

.tool-versions, CHANGELOG.md, build.gradle, gradle.properties, resources/META-INF/changelog.html, src/org/elixir_lang/annotator/ModuleAttribute.kt, src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt, src/org/elixir_lang/injection/markdown/LiteralTextEscaper.kt, src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java, src/org/elixir_lang/reference/ModuleAttribute.kt
- updated gradle dependencies 
- added compatibility with intellij 2022.2
- refactor for compatibility
- elixir version updated
=> Intellij 2022.2 compatibility

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/psi/impl/QualifiableAliasImpl.kt
Fixes #2839
* Stop accumulating qualifiers when bracket operation is hit either as qualifier or argument.
=> Stop accumulating qualifiers when bracket operation is hit either as qualifier or argument

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/leex/reference/resolver/Assign.kt
=> Replace TODO in leex.reference.resolver.Assign with logger errors that include PSiElement

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/injection/markdown/Injector.kt
=> Ignore type for docs

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/mix/Watcher.kt
=> Check if module is disposed when write action is run for syncLibraries

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/Elixir.kt, src/org/elixir_lang/formatter/MixFormatExternalFormatProcessor.kt, src/org/elixir_lang/sdk/erlang_dependent/SdkAdditionalData.java
=> Only use Elixir SDK for `mix format` if it has an Erlang SDK

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/github/issues/create/Request.kt
=> Include more lines of context for stacktraces in error reports

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/injection/markdown/Injector.kt
=> Ignore identifier when @*doc attribute isn't quoted

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/mix/watcher/Resolution.kt
=> Ignore if package virtual file is disposed before the deps can be read

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/injection/markdown/LiteralTextEscaper.kt
=> Check if heredoc has lines before calculating host text range for Markdown docs

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/reference/resolver/Callable.kt
=> Ignore if stubs ids can't be found when resolving Callables

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/DefinitionsScopedSearch.kt, src/org/elixir_lang/code_insight/line_marker_provider/Implementation.kt, src/org/elixir_lang/code_insight/line_marker_provider/Protocol.kt
=> Handle binary modules when processing protocols and implementations for line markers and definition search

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/ecto/Query.kt
=> Skip unqualified no arguments calls when Ecto.Query.from arguments are being typed

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/mix/project/_import/Provider.java, src/org/elixir_lang/mix/project/_import/step/ElixirSdkForModuleStep.kt
=> Filter out Elixir SDKs that don't have an Erlang SDK when importing projects

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/injection/markdown/Injector.kt
=> Log heredoc where markdown cannot be injected

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/injection/markdown/Injector.kt
=> Don't inject markdown in empty heredoc docs

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/UsageTypeProvider.kt
=> Log the accumulated and target usage type that cannot be folded

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/injection/markdown/Injector.kt
=> Ignore group for docs

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/reference/resolver/Type.kt
=> Don't resolve built-in types against the index if index is updating

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/sdk/elixir/Type.kt
=> findModuleForPsiElement in mostSpecificSdk in read action

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/mix/Project.kt
=> Skip finding mix.exs for OTP apps if it can't be read

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/annotator/ModuleAttribute.kt
=> Highlight binary numbers as usual in types

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/annotator/ModuleAttribute.kt
=> Highlight module attributes as usual in types

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/UsageTypeProvider.kt
=> Don't include null target usage types when finding usage type across all targets

CHANGELOG.md, resources/META-INF/changelog.html, src/org/elixir_lang/psi/impl/QualifiableAliasImpl.kt
=> Stop prependingQualifiers at EEx tags.

CHANGELOG.md, build.gradle, gradle.properties, resources/META-INF/changelog.html
Ah the march of time. Seems this should be fairly painless upgrade, so thought I'd start the ball rolling and post here.
Feel free to change anything :).
I also get an error when running `./gradle test`:
```
Unable to load JUnit4 runner to calculate Ignored test cases
```
Full log:
https://gist.github.com/joshuataylor/92e232fb11dee51546353994721a06de
=> Support 233 IDEA (2023.3 release)

gradle.properties, resources/META-INF/changelog.html
=> Redo v18.0.1

CHANGELOG.md, gradle.properties, resources/META-INF/changelog.html
* [#3639](https://github.com/KronicDeth/intellij-elixir/pull/3639) - [@joshuataylor](https://github.com/joshuataylor)
* Support JetBrains Exception Analyzer
* [#3640](https://github.com/KronicDeth/intellij-elixir/pull/3640) - [@joshuataylor](https://github.com/joshuataylor)
* Bump intellij platform gradle to 2.0.1 and IdeaVIM to 2.16.0
=> Add changelog for v19.0.1
