KronicDeth/intellij-elixir

src/META-INF/plugin.xml

It is still unclear to me how to determine what the group names are in this menu.  Using the following config, at very least, it's not first on the list, leaving the generic 'new file' option first.
fixes KronicDeth/intellij-elixir#161
Other repos that do this in various ways: 
https://github.com/Vektah/idea-rust/blob/master/META-INF/plugin.xml
https://github.com/Atsky/haskell-idea-plugin/blob/07b40cd14fbd73a68ad9326f04d7c63f59d6ae09/plugin/META-INF/plugin.xml

Make the new elixir file type last in the NewFile menu

---

.idea/libraries/JInterface.xml
.idea/libraries/erlang.xml
.travis.yml
Makefile
intellij-elixir.iml
intellij-elixir.xml
intellij-erlang.xml
src/META-INF/intellij-erlang-plugin.xml
src/META-INF/plugin.xml
src/org/elixir_lang/Macro.java
src/org/elixir_lang/Util.java
src/org/elixir_lang/annonator/Module.java
src/org/elixir_lang/psi/ModuleDefinition.java

Resolves #84
* Enhancements
* If (1) you have intellij-erlang installed and (2) you have an atom in
Erlang that starts with `Elixir.`, such as `'Elixir.Test'`, then
intellij-elixir will annotate whether it can resolve the name to a
`defmodule` call in Elixir files.

Annotate Erlang Elixir.* Atoms as Modules

---

src/org/elixir_lang/FindUsagesProvider.java

Fixes #199 
The additional clause is adapted from [`com.intellij.lang.java.JavaFindUsagesProvider#getDescriptiveName`](https://github.com/JetBrains/intellij-community/blob/012f5dfa1215fe2aafd85606ede8f32d0f9cadcb/java/java-impl/src/com/intellij/lang/java/JavaFindUsagesProvider.java#L146-L148)
* Bug Fixes
* Fix`IllegalStateException` for file delete and rename by giving `ElixirFile`s descriptive names for safe-refactoring displaying file usage.

Descriptive name for ElixirFile

---

README.md

Fixes #193
* Bug Fixes
* README states explicitly that the plugin works with *both* IntelliJ Community and Ultimate.
* README states that the plugin is free.

Include editions of intellij supported and cost in README

---

src/org/elixir_lang/ElixirSyntaxHighlighter.java

Resolves keyword part of #179.
* Enhancements
* Highlight `after`, `catch`, `do`, `else`, `end, `fn`, and `rescue` as keywords.

Highlight keywords

---

.idea/libraries/JInterface.xml
src/org/elixir_lang/mix/importWizard/MixProjectRootStep.java
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
src/org/elixir_lang/mix/settings/MixConfigurationForm.java

Fixes #224
Supersedes #220
When on Windows, use `mix.bat` instead of just `mix` as `mix` by itself won't run.
* Bug Fixes
* Use `mix.bat` instead of `mix` on Windows and ensure that  the mix version is properly detected even with the Elixir versions < 1.2 where @f-lombardo fixed the mix output in https://github.com/elixir-lang/elixir/pull/4077

Fix mix version detection on Windows

---

gen/org/elixir_lang/psi/ElixirContainerAssociationOperation.java
gen/org/elixir_lang/psi/impl/ElixirContainerAssociationOperationImpl.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/annonator/ModuleAttribute.java
src/org/elixir_lang/psi/AssociationOperation.java

Extends #223
* Enhancements
* Annotate left and right types when `=>` is used in maps in types.

Support associations (=>) in types

---

.travis.yml
elixir.xml
tests/org/elixir_lang/parser_definition/MatchedArrowOperationParsingTestCase.java
tests/org/elixir_lang/parser_definition/ParsingTestCase.java

Test against both Elixir 1.1.1 and 1.2.0 on Travis-CI.
* Enhancements
* Test against both Elixir 1.1.1 and 1.2.0 on Travis-CI (instead of just Elixir 1.1.1)

Test against Elixir 1.2.0

---

src/org/elixir_lang/sdk/ElixirSdkRelease.java
src/org/elixir_lang/sdk/ElixirSdkType.java

Fixes #238
* Enhancements
* Get the Elixir version directly from `System.build_info[:version]` instead of processing the formatted output of `elixir --version` as the build info version is more stable.
* Bug Fixes
* Elixir version parsing handles both pre and build numbers if present by using the same regular expression as Elixir itself uses for the `Version` module.

Use elixir -e instead of --version

---

src/org/elixir_lang/structure_view/element/CallDefinition.java
src/org/elixir_lang/structure_view/element/CallDefinitionClause.java
src/org/elixir_lang/structure_view/element/call_definition_by_name_arity/TreeElementList.java
src/org/elixir_lang/structure_view/element/modular/Module.java
src/org/elixir_lang/structure_view/node_provider/Used.java

* Bug Fixes
* Handle there being no primary arguments for call definitions as can be the case when the function name hasn't been typed yet, which previously caused a failing assert.

Better error handling in Structure

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/parser_definition/infix_parsing_test_case/Issue251.ex
testData/org/elixir_lang/parser_definition/infix_parsing_test_case/Issue251WithNoLeftOperand.ex
testData/org/elixir_lang/parser_definition/infix_parsing_test_case/WellFormed.ex
tests/org/elixir_lang/parser_definition/InfixParsingTestCase.java

Fixes #251
* Bug Fixes
* Allow `Infix#operator` to work on operations with errors, which eliminates the `AssertionError` reported when typing infix operation and they are incomplete.

Eliminate the AssertionError reported when typing infix operations

---

src/org/elixir_lang/ElixirColorSettingsPage.java

* Bug Fixes
* Add Keywords to the Preferences > Editor > Colors & Fonts > Elixir settings page, so it can be customized for just Elixir instead of having to change Preferences > Editor > Colors & Fonts > General > Keyword.

Add Keywords to Colors & Fonts

---

.idea/misc.xml
.idea/runConfigurations/Elixir.xml
.travis.yml
elixir.xml
idea.xml
intellij-elixir.xml
intellij_elixir.xml
module_intellij-elixir.xml
src/org/elixir_lang/ElixirSyntaxHighlighter.java
src/org/elixir_lang/action/CreateElixirModuleAction.java
src/org/elixir_lang/mix/settings/MixConfigurationForm.java
tests/org/elixir_lang/parser_definition/ElixirLangElixirParsingTestCase.java

Fixes #230
Fixes #250
Fixes #258
* Enhancements
* Build against 14.0, 14.1, 15.0, and 2016.1 on travis-ci to ensure continued compatibility.
* Bug Fixes
* Use `TextAttributesKey`s that aren't deprecated in 2016.1 and work back to 14.1
All of `CodeInsightColors` is deprecated, so all constants from there had to be replaced.  Unfortunately, the recommended replacements don't have the same color as the original, so I used different `DefaultLanguageHighlighterColors` constants for some.
"Module Attribute" is now based on `DefaultLanguageHighlighterColors.CONSTANT` (which is purplish in Darcula) instead of the recommended `METADATA`, which is yellow.  Although module attributes don't have to be constant since they can be set to accumulate, often they are used as constants and not really as …

Ensure compatibility from 14.0 to 2016.1

---

src/org/elixir_lang/action/CreateElixirModuleAction.java

Fixes #191
* Bug Fixes
* Instead of showing the regular expression pattern, which may be confusing to new developers, explain in English the expected pattern.  I also included the description, which explains how nesting is mapped to
directories, of the action since it doesn't actually show up in the dialog otherwise.

Use more human-readable error message for Elixir File action

---

src/org/elixir_lang/structure_view/element/CallDefinitionClause.java

* Bug Fixes
* Fix (one cause) of `AssertionError` in `GoToSymbolContributor` when the `Modular` (`defimpl`, `demodule`, `defprotocol`, and `quote`) could not be resolved due a `def` being surrounded by a `for` comprehension, which is common in Elixir libraries as was the case for `Postgrex`: any enclosing `for` comprehension(s) will now be ignored and the next enclosing macro will be checked to see if it is a `Modular`.

Strip for comprehensions surrounding definitions when finding Modular

---

src/META-INF/plugin.xml
src/org/elixir_lang/annonator/ModuleAttribute.java
src/org/elixir_lang/errorreport/Logger.java
src/org/elixir_lang/errorreport/Submitter.java
src/org/elixir_lang/errorreport/Task.java
src/org/elixir_lang/github/issues/create/Request.java
src/org/elixir_lang/navigation/GotoSymbolContributor.java
src/org/elixir_lang/psi/UnqualifiedNoArgumentsCall.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

* Enhancements
* Custom error handling that will open an issue against https://github.com/KronicDeth/intellij-elixir with the exception messsage and stacktrace filled in.
* Changed `NotImplementedExceptions` and (some) `assert`s to logging custom error message that include the `PsiElement` text and the containing file as an attachment.  The files make the URL too big for the error handler to put the file contents in when opening the browser with the error handler, so the issue body instead explains how to get the attachment text out of IntelliJ's "IDE Fatal Errors"

Error handler

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

* Bug Fixes
* Use the error reporter logger instead of plain `assert` in `Prefix#operator`.  **NOTE: This does not address error recovery recovery since I don't have a regression test case.**

Use error reporter instead of assert in Prefix#operator

---

src/org/elixir_lang/FindUsagesProvider.java

Fixes #277 
* Bug Fixes
* All function name elements act as `PsiNameIdentifier`s now even if they don't resolve, but that means they all need to support `FindUsagesProvider#getType`, which they don't, so use a placeholder of "unknown call type" for any `Call` that can't be matched and "unknown element" for anything else.

Always have a FindUsagesProvider#getType

---

src/org/elixir_lang/annonator/ModuleAttribute.java

Fixes #311
* Leave normal highlighting for char tokens when highlighting types

Leave normal highlighting for char tokens when highlighting types

---

src/META-INF/plugin.xml
src/org/elixir_lang/ElixirSyntaxHighlighter.java
src/org/elixir_lang/annonator/Atom.java

Resolved #282
* Highlight keyword keys (`key:` in `key: value`) that aren't quotes (`"key": value` or `'key': value`) as Atom.

Highlight keyword keys that aren't quotes as Atom

---

.idea/libraries/idea.xml
.idea/misc.xml
CONTRIBUTING.md
intellij-elixir.iml
jps-builder/jps-builder.iml
jps-builder/src/org/elixir_lang/jps/builder/ElixirBuilder.java
jps-builder/src/org/elixir_lang/jps/builder/ExecutionException.java
jps-builder/src/org/elixir_lang/jps/builder/GeneralCommandLine.java
jps-builder/src/org/elixir_lang/jps/builder/ParametersList.java
jps-builder/src/org/elixir_lang/jps/builder/ParamsGroup.java
jps-builder/src/org/elixir_lang/jps/builder/ProcessNotCreatedException.java
jps-shared/jps-shared.iml

Fixes #290
Fixes #293
Fixes #295
Fixes #302
Fixes #313
* In IntelliJ 14.1, all of `openapi.jar` targets Java 1.6 (with `MAJOR.MINOR` `50.0`), but in IntelliJ 2016.1, some of `openapi.jar` targets only Java 1.8 (with `MAJOR.MINOR` `52.0`), since `jps-builders` require parts of `openapi.jar` and must target Java 1.6 even for IntelliJ 2016.1, the `52.0` `.class`es needed to be ported into `org.elixir_lang.jps.builder`, so that the `52.0` version in `openapi.jar` wouldn't be attempted to be loaded.
This ended up being 5 classes:
* `ExecutionException`
* `GeneralCommandLine`
* `ParametersList`
* `ParamsGroup`
* `ProcessNotCreatedException`
Only `GeneralCommandLine` was used directly, all others are dependencies
of it.
Thanks to @cedriessen for pointing that all the weird loading bugs were …

Build jps-builder using only Java 1.6 compatible .classes

---

src/org/elixir_lang/psi/scope/Variable.java

Fixes #326
* Check if `parameter` is `null` before `Variable#execute` call in `Variable#execute(PsiElement[], ResolveState)`.

Check if parameter is null before Variable.execute call

---

gen/org/elixir_lang/psi/ElixirMatchedWhenOperation.java
gen/org/elixir_lang/psi/ElixirUnmatchedWhenOperation.java
gen/org/elixir_lang/psi/ElixirVisitor.java
src/META-INF/plugin.xml
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/annonator/ModuleAttribute.java
src/org/elixir_lang/code_insight/line_marker_provider/CallDefinition.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/reference/CallDefinitionClause.java
src/org/elixir_lang/structure_view/element/CallDefinitionClause.java
src/org/elixir_lang/structure_view/element/CallDefinitionSpecification.java

* Show a function separator (Preferences > Editor > General > Appearance > Show method separators) above the group of `@doc`, `@spec` and `def`, `defp`, `defmacro`, and `defmacrop` (call definition clauses) of the same name and arity range.  Arity range will be used if one of the call definition clauses uses default arguments.

Function separator

---

src/org/elixir_lang/annonator/Kernel.java
src/org/elixir_lang/psi/call/name/Function.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/reference/Callable.java

Fixes #327
* Fix `isVariable` and `variableUseScope` for `var!(name)[...]`

Fix isVariable and variableUseScope for var!(config)[:url]

---

.idea/runConfigurations/org_elixir_lang.xml
src/org/elixir_lang/psi/FoldingBuilder.java
src/org/elixir_lang/psi/scope/module_attribute/Implementation.java
src/org/elixir_lang/psi/scope/module_attribute/implemetation/For.java
src/org/elixir_lang/psi/scope/module_attribute/implemetation/Protocol.java
src/org/elixir_lang/psi/scope/variable/MultiResolve.java
src/org/elixir_lang/reference/ModuleAttribute.java
src/org/elixir_lang/structure_view/element/CallDefinitionClause.java
src/org/elixir_lang/structure_view/element/modular/Implementation.java

Resolves #304
- `@for` folds to the resolved module name in `defimpl`
- `@protocol` folds to the protocol name in `defimpl`
- `@for` is no longer marked as unresolved in `defimpl` and instead resolve to the either the `<name>` in `for: <name>` or the module name for the enclosing module when `for: ` is not given.
- `@protocol` is no longer marked as unresolved in `defimpl` and instead resolve to the `<name`> in `defimpl <name>`.

Resolve and fold both @for and @protocol in defimpl

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

Fixes #339
* Instead of `assert checkRight || checkLeft` in `Match.processDeclaraions`, do the normal code if `checkRight || checkLeft` and log an error report otherwise, so that the exact code that trigger this error can be reported and the method fixed to handle that form of `Match` later.

Use error logger instead of naked assert of processDeclarations(Match

---

src/org/elixir_lang/mix/settings/MixConfigurationForm.java
src/org/elixir_lang/sdk/ElixirSdkType.java
src/org/elixir_lang/sdk/ElixirSystemUtil.java

Fixes #329
* Share code between `mix --version` parsing and `elixir` version parsing.
* Check all lines of output for mix version as Elixir 1.3.0 changed the format of `mix --version`, so that it includes the Erlang header (`Erlang/OTP ... [erts-...] [source] [64-bit] [smp:..:..] [async-threads:..] [hipe] [kernel-poll:false] [dtrace]`) on the first line and `Mix <version>` on the 3rd line.  Previously the parsing expected `Mix <version>` to be the first line.

Be able to parse mix version from 1.3.0+

---

src/org/elixir_lang/navigation/item_presentation/modular/Module.java
src/org/elixir_lang/navigation/item_presentation/modular/Unknown.java
src/org/elixir_lang/structure_view/Model.java
src/org/elixir_lang/structure_view/element/CallDefinitionClause.java
src/org/elixir_lang/structure_view/element/File.java
src/org/elixir_lang/structure_view/element/modular/Module.java
src/org/elixir_lang/structure_view/element/modular/Unknown.java

Fixes #332
* Allow Unknown modulars in the Structure pane, in addition to Go To Symbol.  Their icon is a big ? to indicate their correct usage is unknown.
* If no known modular (Module, Implementation, Protocol, Quote, or Use) matches the call, then use Unknown, which accepts any macro with a `do` block or keyword.  This allows Go To Symbol to no error in projects using Dogma as `defrule` is now treated as Unknown instead of causing an error that the enclosing modular could not be found.

Add Unknown modular for custom macros that behave like Modules

---

src/org/elixir_lang/psi/BracketOperation.java
src/org/elixir_lang/psi/QualifiedBracketOperation.java
src/org/elixir_lang/psi/UnqualifiedBracketOperation.java
src/org/elixir_lang/reference/Callable.java

Fixes #346
* Have both `QualifiedBracketOperation` and `UnqualifiedBracketOperation` extend `BracketOperation`, so that `BracketOperation` can be used to match both when the qualification does not matter.
* `BracketOperations` are neither parameters nor variables.

BracketOperations no longer break isParameter or isVariable

---

src/org/elixir_lang/console/FileReferenceFilter.java

Fixes #229
* Strip spaces from front of file path in `mix` output, which allows file looks to work correctly.
* Ensure file reference highlight doesn't include the leading and trailing characters by fix off-by-one errors.

Fix latent bugs causing bad file linking in stacktraces

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/operation/infix/Position.java
src/org/elixir_lang/psi/operation/infix/Triple.java

Fixes #352
* Determine whether to check left, right, or both by doing isAncestor checks for all operands, not just the normalized operand.  The normalized operand is still used for PsiSceopProcessor#execute since execute is not expected to handle error elements.

Check all left or rigth operands instead of normalized operands in match

---

src/org/elixir_lang/navigation/item_presentation/modular/Module.java

Fixes #255
* The `Module` icon got the same icon as `Unknown` when creating `Unknown` somehow, I assume due to find-replace.

Revert incorrect find-replace when Unknown was introduced

---

src/META-INF/plugin.xml
src/org/elixir_lang/BraceMatcher.java
src/org/elixir_lang/QuoteHandler.java
src/org/elixir_lang/TypedHandler.java
src/org/elixir_lang/lexer/StackFrame.java

Resolves #357
* `BraceMatcher`
* Matches the following pairs:
* `do` to `end`
* `fn` to `end`
* `"""` to `"""`
*  `'''` to `'''`
* `<<` to `>>`
* `<` to `>`
* `[` to `]`
* `{` to `}`
* `(` to `)`
* Completes the following pairs:
* `[` with `]`
* `{` with `}`
* `(` with `)`
* `QuoteHandler` completes standard quotes (that start with `"` or `'`)
* `'` with `'`
* `"` with `"`
* `'''` with `'''`
* `"""` with `"""`
* `TypedHandler` completes the non-standard quotes and braces
* `do` with ` end`
* `fn` with ` end`
` `<<` with `>>`
* `<` with `>`  (for promoters)
* `/` with `/`  (for promoters)
* `|` with `|` (for promoters)

Auto-insert matching delimiters

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

Fixes #369
* `enclosingMacroCall` could climb out the stab after a `do`, but not the `else` in an `if`, which is used for defined functions conditionally in [`Phoenix.Endpoint.server/0`](https://github.com/phoenixframework/phoenix/blob/v1.2.0/lib/phoenix/endpoint.ex#L542-L548)

Add support for `else` (or `after`, `catch`, or `rescue`) to enclosingMacroCall

---

res/liveTemplates/Elixir.xml

Resolves #294
* A lot of ppl use the doc template after already typing @, but the `doc` template starts with `@`, so it ends up inserting `@@doc ...`.  The `@doc` is the same code, but since the name starts with `@`, it doesn't insert a second `@`.  Unfortunately, the template search code doesn't prompt when just typing `@`, so you end up having to type `@doc` before only one template is selected.  The `@doc` template will show in the lookup as soon as `@d` is typed, but you have to select it from the list then before tabbing to accept.

Add @doc template

---

src/org/elixir_lang/TypedHandler.java

Fixes #376
* Look at end of `do` instead of start for `end` completion to stop ignoring the `:` in `do: `, when `caret - 3` would land on the `o`, now all tests are meant to land on the `o`, so `do: ` won't complete with `end` incorrectly anymore.

Look at end of `do` instead of start for `end` completion

---

src/org/elixir_lang/annonator/ModuleAttribute.java

Fixes #375
* Ignore `ElixirVariable` in `highlightTypesAndTypeParameterUsages`

Ignore ElixirVariable in highlightTypesAndTypeParameterUsages

---

src/org/elixir_lang/Module.java
src/org/elixir_lang/annonator/Kernel.java
src/org/elixir_lang/psi/ElementDescriptionProvider.java
src/org/elixir_lang/psi/call/name/Function.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/scope/Module.java
src/org/elixir_lang/psi/scope/MultiResolve.java
src/org/elixir_lang/psi/scope/Variable.java
src/org/elixir_lang/psi/scope/module/MultiResolve.java
src/org/elixir_lang/psi/scope/variable/MultiResolve.java
src/org/elixir_lang/reference/Callable.java
src/org/elixir_lang/reference/Module.java
src/org/elixir_lang/reference/ModuleAttribute.java
src/org/elixir_lang/reference/module/ResolvableName.java
src/org/elixir_lang/structure_view/element/CallDefinitionClause.java

Resolves #377
* Resolve aliased modules to their `alias` call, from the alias call, you can Go To Declaration for the module itself.
* Code structure
* Module resolution uses the OpenAPI convention of `treeWalkUp` now instead of custom code.
* Resolvable names has been extracted to its own class
* Resolution use cases
* `Suffix` resolves to `alias Prefix.Suffix`
* `Suffix.Nested` resolves to `alias Prefix.Suffix`
* `As` resolves `to `alias Prefix.Suffix, as: As`
* `NestedSuffix` resolves to `alias __MODULE__.NestedSuffix`

Resolve aliased modules

---

src/org/elixir_lang/psi/scope/module/MultiResolve.java
src/org/elixir_lang/psi/scope/module/Variants.java
src/org/elixir_lang/reference/Module.java

Resolves #88
* Completion for module aliases
* From in-file aliases
* `__MODULE__`
* In project modules (using index already used for Go To Declaration)

Module completion for file aliases and project modules

---

src/org/elixir_lang/psi/scope/module/CreateLookupElement.java
src/org/elixir_lang/psi/scope/module/Longer.java
src/org/elixir_lang/psi/scope/module/ProperStartsWith.java
src/org/elixir_lang/psi/scope/module/ReplaceFirst.java
src/org/elixir_lang/psi/scope/module/StartsWith.java
src/org/elixir_lang/psi/scope/module/Variants.java
src/org/elixir_lang/reference/Module.java

Fixes #394 
* When a aliased name is added to the module list for completion, it's unaliased name is searched for in the `AllName` index, if any nested modules are found for the unaliased name, then those nested names are aliased and also shown for completion.

Module names nested under aliases module names show up in completion

---

src/org/elixir_lang/psi/scope/module/Variants.java

Fixes #398 
* `resolvableName` allows nested modules under multiple aliases to be completed.

Use resolvableName when completing aliases nested modules

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

Fixes #396
* Look outside Enum.map for enclosing macro call because `Ecto` defines the clauses of `__schema__(:type, ...)` using `Enum.map`, but `enclosingMacroCall` only knews to jump over enclosing macros like `for`, so a special case was added for anonymous function given to `Enum.map`.
* Fix if-else-ordering bug where `Call` appeared before operations (which are usually `Call`s) like `Match`.

Look outside Enum.map for enclosing macro call

---

src/META-INF/plugin.xml
src/org/elixir_lang/folding/Builder.java
src/org/elixir_lang/folding/ElixirFoldingSettings.java
src/org/elixir_lang/folding/OptionsProvider.java

Resolves #368 
* By user request, the folding will be off-by-default now, but can be re-enabled, like the old behavior by checking the checkbox in Preferences > Editor > General > Code Folding > Elixir Module directive (`alias`, `import`, `require` or `use`) groups.

Allow folding of Module directive groups to be configured

---

gen/org/elixir_lang/psi/ElixirUnmatchedQualifiedAlias.java
gen/org/elixir_lang/psi/impl/ElixirMatchedQualifiedAliasImpl.java
gen/org/elixir_lang/psi/impl/ElixirUnmatchedQualifiedAliasImpl.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/scope/module/MultiResolve.java
src/org/elixir_lang/psi/scope/module/Variants.java
src/org/elixir_lang/reference/module/ResolvableName.java
src/org/elixir_lang/reference/module/UnaliasedName.java

Fixes #404
* Resolve `as:` aliased name to both `alias` and `defmodule`
* Complete modules nested under `as:` aliased name.
* Resolve alias nested under aliased modules to both the `alias` and `defmodule`, as resolving to only the `alias` loses the nested name, so it wasn't possible to jump to the nested name's `defmodule.
* Resolve aliased name to both the `alias` and the `defmodule`, so you can skip jumping to the `alias` before jumping to the `defmodule`.

Multiresolve to alias and defmodule

---

src/org/elixir_lang/reference/Callable.java

Fixes #367
* Include element class in Callable logged errors because sometimes, the excerpt doesn't have enough context, and it's not safe to search for more context (as those PSI walking methods have also had errors before), so include the element class in the message, which has the benefit that most times the bugs are fixed by adding that class or an interface of that class to one of the methods AND it will make the error message different, so that users don't think other users have the same error and jump on the issue instead of opening a new one.
* `ElixirNoParenthesesStrict` can occur in `def (conn, %{}) do\nend` when a template is used, so there is no name for `def`.  Since the intent is known, mark `conn` as a parameter by checking the parent of the `ElixirNoParenthesesStrict`, …

Look through NoParenthesesStrict for parameters

---

src/org/elixir_lang/annonator/ModuleAttribute.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/annotator/module_attribute/typespec_test.exs
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #412
Fixes #413
Fixes #414
* Regression test using `typespec_test.exs` that triggered #413.
* Return empty `Set` instead of `null` from `canonicalNameSet`
* Highlight types in `ElixirMapUpdateArguments` even though they are an [invalid typespec example from elixir-lang/elixir tests](https://github.com/elixir-lang/elixir/blob/dadf98fbff2966f24bf5b0313822a90b90f7016a/lib/elixir/test/elixir/kernel/typespec_test.exs#L314-L320)

Fix indexing and type highlighting for elixir-lang/elixir

---

src/org/elixir_lang/annonator/ModuleAttribute.java

* Check if `rightOperand` is `null` when highlighting types for `Type`, which can occur when typing `:` for an atom after the `::` for a `Type`.

Check if rightOperand is null when highlighting types

---

gen/org/elixir_lang/parser/ElixirParser.java
tests/org/elixir_lang/parser/ElixirParserTest.java

Fixes #415
* Regression test that checks the correct `import` is used for `GeneratedParserUtilBase` in `ElixirParser`.
* Use `GeneratedParserUtilBase` synced to GrammarKit version as was done originally in

Use GeneratedParserUtilBase synced to GrammarKit version and test for it

---

src/org/elixir_lang/reference/Callable.java

Fixes #416
* Check parent of `BracketArguments` for `isParameter` and `isVariable`

Check parent of `BracketArguments` for `isParameter` and `isVariable`

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

Fixes #417
* Instead of asserting that a `QualifiableAlias` has 3 children, which may not be true on error recovery, use the `Normalized` static methods that are used elsewhere to handle error recovery around Infix operations as the `.` in `QualifiableAlias`es is a pseudo-Infix.

Replace assert with Normalized

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_429/get_use_scope.ex
tests/org/elixir_lang/reference/callable/Issue429Test.java

Fixes #429
* Regression test for #429
* 	Search above block items and block lists for calls to check use scope

Search above block items and block lists for calls to check use scope

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_422/is_variable.ex
tests/org/elixir_lang/reference/callable/Issue422Test.java

* Failing regression test for #422
* Check parent `isVariable` for `ElixirNoParenthesesManyStrictNoParenthesesExpression`

Check parent `isVariable` for `ElixirNoParenthesesManyStrictNoParenthesesExpression`

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/missing_type_operator.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #438
* Failing regression test for #438
* Highlight `@type` without `::`

Highlight @type without :: 

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_431/planet.ex
tests/org/elixir_lang/reference/callable/Issue431Test.java

Fixes #431
* Failing regression test for #431
* `ElixirNoParenthesesManyStrictNoParenthesesExpression` indicates an ambigious no parentheses nesting, but the highlighting should not error and do a best effort instead.

Check if parent isParameter for ElixirNoParenthesesManyStrictNoParenthesesExpression

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_436/is_parameter.ex
tests/org/elixir_lang/reference/callable/Issue436Test.java

Fixes #436
* Regression test for #436
* `isParameter(Call)` called `isParameter` on its parent if it wasn't a call definition clause, delegation or macro, but `isParameter(PsiElement)` immediately calls `getParent()` and does all the `instanceof` tests on the parent.  So, instead of `isParameter(Call)` calling `isParameter(PsiElement)` on its parent, it should just call it on itself, this way the check for `ElixirInterpolation` will not be skipped and there's no need to handle `ElixirInterpolatedString`.

Don't skip Call's parent when checking types in isParameter

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/psi/operation/prefix/zero_operands.ex
tests/org/elixir_lang/psi/operation/PrefixTest.java

Fixes #446
* Regression test for #446
* Don't do a naked `assert` that there are 2 children because this can fail during error recovery on the operand, instead use the `prefix.Normalized.operand()` through `prefix.operand()`.
**WARNING: This changes the `@NotNull` array so that its sole element changes from
`@NotNull` to `@Nullable`.  It may trigger new bugs.**

Use Normalized operator for Prefix primaryArguments

---

src/org/elixir_lang/psi/scope/Variable.java

Fixes #460
* Use shipped `GeneratedParserUtilBase.DUMMY_BLOCK` because the `DUMMY_BLOCK` *MUST* match the `GeneratedParserUtilBase` to detect dummy blocks inserted for error handling.

Use shipped GeneratedParserUtilBase.DUMMY_BLOCK

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_456/is_variable.ex
tests/org/elixir_lang/reference/callable/Issue456Test.java

Fixes #456
* Regression test for #456
* Skip over `ElixirNoParenthesesStrict` for `isVariable`

Skip over ElixirNoParenthesesStrict for isVariable

---

src/org/elixir_lang/annonator/Parameter.java
src/org/elixir_lang/code_insight/highlighting/brace_matcher/NonTrivial.java
src/org/elixir_lang/psi/scope/call_definition_clause/Variants.java
testData/org/elixir_lang/psi/scope/call_definition_clause/variants/self_completion.ex
tests/org/elixir_lang/psi/scope/call_definition_clause/VariantsTest.java

Fixes #462
* Check if `iterator.atEnd()` before calling `iterator.getTokenType()` to avoid `IndexOutOfBounds` exception.
* Don't add current call definition clause being written to completion

Don't add current call definition clause being written to completion 

---

src/org/elixir_lang/structure_view/element/CallDefinitionHead.java
testData/org/elixir_lang/structure_view/element/call_definition_head/issue_468.ex
testData/org/elixir_lang/structure_view/element/call_definition_head/no_when.ex
testData/org/elixir_lang/structure_view/element/call_definition_head/single_when.ex
tests/org/elixir_lang/structure_view/element/CallDefinitionHeadTest.java

Fixes #468
* Regression test ofr #468
* When#leftOperand will return null (because it's normalized) if there are left-hand error elements, but when stripping guards we want best-effort to match human expectations, so don't use normalized null, but use left, non-error element if it is unique.

stripGuard handles errors in left operand for when

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_469.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #469
* Regression test for #469
* Highlight Strings and String Heredocs as errors in types.
* Highlight types in `QualifiedNoParenthesesCall`

Highlight types in QualifiedNoParenthesesCall

---

src/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClause.java
testData/org/elixir_lang/code_insight/lookup/element_renderer/call_definition_clause/issue_457.ex
tests/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClauseTest.java

Fix #457
* Still not obvious why `name` for a `CallDefinitionClause` lookup renderer can be longer than `presentableText`, so still log an error, but with `Logger.error`, so we get `name`, `presentableText`, and the original `element`.

Check if name is longer than presentable text of CallDefinitionClause

---

src/org/elixir_lang/psi/scope/variable/MultiResolve.java
testData/org/elixir_lang/issue_470/in_match_in_match.ex
testData/org/elixir_lang/issue_470/in_match_match.ex
testData/org/elixir_lang/issue_470/in_match_match_match.ex
testData/org/elixir_lang/issue_470/match_in_match.ex
testData/org/elixir_lang/issue_470/match_in_match_match.ex
testData/org/elixir_lang/issue_470/match_match.ex
tests/org/elixir_lang/Issue470.java

Fixes #470
* Failing regression test for #470
* Skip `Arguments` elements in `previousParentExpresion` to eliminate an unnecessary level of processing declarations since calls will enter their arguments.
* Only put new `ENTRANCE` in `ResolveState` in `variable.MultiResolve.resolveResultList`, so that caller can override the default value.
* Set `ENTRANCE` to `matchAncestor` instead of previous expression to eliminate the looping that occurred when a variable was unbound (or a function) because the check for `with` (and `for`) was expecting the `ENTRANCE` to be the previous child expression instead of the `with`
clause as a whole (or the `Arguments` element as had been the case before
6fcc19b).

Set ENTRANCE to matchAncestor instead of previous expression

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_471.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #471
* Failing regression test for #471
* Don't type-highlight `BracketOperation`s as they occur when putting maps or structs in front of lists.

Don't type highlight BracketOperations

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_472.ex
tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java

Fixes #472
* Regression test for #472.
* Treat `Enum.each` the same as `Enum.map` around `def`

Treat Enum.each the same as Enum.map around def

---

gen/org/elixir_lang/psi/ElixirMatchedArrowOperation.java
gen/org/elixir_lang/psi/ElixirUnmatchedArrowOperation.java
gen/org/elixir_lang/psi/ElixirVisitor.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/operation/Arrow.java
testData/org/elixir_lang/reference/callable/issue_480/aliased_module_qualifier.ex
testData/org/elixir_lang/reference/callable/issue_480/direct_module_qualifier.ex
testData/org/elixir_lang/reference/callable/issue_480/double_aliased_module_qualifier.ex
testData/org/elixir_lang/reference/callable/issue_480/local.ex
testData/org/elixir_lang/reference/callable/issue_480/map_access_qualifier.ex
testData/org/elixir_lang/reference/callable/issue_480/referenced.ex
testData/org/elixir_lang/reference/callable/issue_480/remote.ex
testData/org/elixir_lang/reference/callable/issue_480/unresolved_alias_qualifier.ex
tests/org/elixir_lang/reference/callable/Issue480Test.java

Fixes #480
* Extract `Arrow` interface for `*ArrowOperation`s.
* Regression tests for #480
* Increase `resolvedFinalArity` by `1` for piping.

resolvedFinalArity takes into account piping

---

src/org/elixir_lang/mix/runner/MixRunConfigurationBase.java
src/org/elixir_lang/mix/runner/MixRunConfigurationEditorForm.form
src/org/elixir_lang/mix/runner/MixRunConfigurationEditorForm.java
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java

Fixes #216 
Fixes #502 
* Use the `CommonProgramParametersPanel` to get the working directory and environment variables the same way the JUnit form does.  Replace the custom "Command" input with the "Program arguments" input built into the `CommonProgramParametersPanel`. `CommonProgramParametersPanel` expects to store the "Program Arguments" in a "ProgramParameters" field, so old run
configurations will lose their "Command" option value and it will be migrated to the new "ProgramParameters".
* Fix typo: `myRunInModuleChekcBox` => `myRunInModuleCheckBox`

Working directory and Environment Variables for Mix Run Configurations

---

jps-shared/src/org/elixir_lang/jps/mix/MixSettingsState.java
res/exunit/team_city_ex_unit_formatter.ex
res/exunit/test_with_formatter.ex
src/META-INF/plugin.xml
src/org/elixir_lang/exunit/ElixirModules.java
src/org/elixir_lang/mix/importWizard/MixProjectImportBuilder.java
src/org/elixir_lang/mix/runner/MixRunConfigurationBase.java
src/org/elixir_lang/mix/runner/MixRunConfigurationEditorForm.java
src/org/elixir_lang/mix/runner/MixRunningState.java
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfiguration.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfigurationEditorForm.form
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfigurationEditorForm.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfigurationFactory.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfigurationProducer.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfigurationType.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunner.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunningState.java
src/org/elixir_lang/mix/settings/MixConfigurationForm.form
src/org/elixir_lang/mix/settings/MixConfigurationForm.java
src/org/elixir_lang/mix/settings/MixSettings.java
src/org/elixir_lang/sdk/ElixirSdkRelease.java
src/org/elixir_lang/settings/ElixirExternalToolsConfigurable.java

This adds ExUnit test integration using the `mix test` command. It supports creating a run configuration manually or from a PSI element, meaning you can use the usual shortcut to run the test at the cursor's position, or run individual test files or directories. You can even right click on a particular test result to re-run just that test.
The latest elixir release (1.3.4) does not support specifying a custom test formatter on the CLI, but I submitted a change to enable that and it's been merged into master, so it should be released at some point. Until it is, I've bundled a custom mix task `TestWithFormatter`. Based on the Mix version in the "External Tools" settings, we guess whether this custom task is necessary or not.
I think the branch currently works, but it could use improvements …

Add Mix ExUnit run configuration

---

src/META-INF/plugin.xml
src/org/elixir_lang/mix/TestFinder.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

Resolves #449
* `enclosingMacroCall` returns enclosing macro call when parent is `ElixirDoBlock`, so that `end` element goes to the macro call.
* `Nagivate > Test` will go to the Module that has the same canonical name as the current `defimpl`, `defmodule`, `defprotocol` , or `quote` with a `Test` suffix added
* `Navigate > Test Subject` will go to the `defimpl`, `defmodule`, `defprotocol`, or `quote` that has the same canonical name as the current Module with the `Test` suffix removed.

Navigate > Test and Navigate > Test Subject

---

src/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClause.java
tests/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClauseTest.java

Fixes #503
* Don't log error when name length exceeds presentable text length because it appears to be common for normal users and not a development environment artifact.

Don't log error when name length exceeds presentable text length

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_500/is_variable.ex
tests/org/elixir_lang/reference/callable/Issue500Test.java

* Regression test for #500
* Check parent of `ElixirMultipleAliases` for `isVariable` because `ElixirMultipleAliases` can be hit in `isVariable` when `MyAlias.` is added on a line above a pre-existing tuple, such as when typing a new qualified call.

Check parent of `ElixirMultipleAliases` for `isVariable`

---

src/org/elixir_lang/code_insight/lookup/element_renderer/Variable.java

Fixes #506
* Add space between variable and match in lookup element presentation

Add space between variable and match in lookup element presentation

---

src/org/elixir_lang/errorreport/Logger.java

Fixes #520
* Check `VirtualFile` is not null before creating attachment because `PsiFile` can lack a `VirtualFile` if the `PsiFile` only exists in memory.

Check VirtualFile is not null before creating attachment

---

src/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClause.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/structure_view/element/CallDefinition.java
src/org/elixir_lang/structure_view/element/CallDefinitionClause.java

Fixes #507
* Convert `CallDefinitionClause(Call)` to `CallDefinitionClause.fromCall(Call)`, so that `null` can be returned when `CallDefinitionClause.enclosingModular(Call)` returns `null`.

CallDefinitionClause(Call) -> CallDefinitionClause.fromCall(Call)

---

src/org/elixir_lang/code_insight/completion/provider/CallDefinitionClause.java
src/org/elixir_lang/psi/Import.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/scope/module/MultiResolve.java
src/org/elixir_lang/reference/Callable.java
src/org/elixir_lang/reference/Module.java

Fixes #511
Fixes #512
Fixes #529
Fixes #538
* Use `functionName` instead of `getName` when multiresolving unqualified functions because `getName` will return the Alias when called on `defmodule`.
* `maybeQualifiedCallToModular` returned `null` BOTH (1) if the call was unqualified OR (2) if the call was qualified, but its modular could not be resolved, so qualified calls to `.beam`-only modules, like `File.read!` returned `null` because `File` could not be resolved to a modular.  Remove `maybeqQualifiedToModular` and call `qualifiedToModular` when `myElement` is qualified.  If the modular is `null`, then return an empty `ResolveResult[]` instead of looking for unqualified matches.
* Pass `maxScope` to `Module` reference.  `maxScope` is generally the containing file for the element, but …

Prevent StackOverflow when resolving import aliases by limiting scope to parent

---

src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_517/variable_use_scope.ex
tests/org/elixir_lang/reference/callable/Issue517Test.java

Fixes #517
* Regression test for #517
* A variable cannot be declared in update arguments, so return `LocalSearchScope.EMPTY`, the same as interpolation.

LocalSearchScope.EMPTY for ElixirMapUpdateArguments variableUseScope

---

src/org/elixir_lang/sdk/ElixirSystemUtil.java
tests/org/elixir_lang/sdk/ElixirSystemUtilTest.java

Fixes #521
* Regression test for #521
* `ElixirSystemUtil.getProcessOutput` already allowed for an empty, invalid `ProcessOutput` when the `workDir` wasn't a directory, so allow it to also be null and return the empty `ProcessOutput`.

Allow ElixirSystemUtil.getProcessOutput workDir to be null

---

res/inspectionDescriptions/KeywordPairColonInsteadOfTypeOperator.html
res/inspectionDescriptions/MatchInsteadOfTypeOperator.html
src/META-INF/plugin.xml
src/org/elixir_lang/annonator/ModuleAttribute.java
src/org/elixir_lang/inspection/KeywordPairColonInsteadOfTypeOperator.java
src/org/elixir_lang/inspection/MatchOperatorInsteadOfTypeOperator.java
src/org/elixir_lang/local_quick_fix/ConvertKeywordPairToTypeOperation.java
src/org/elixir_lang/local_quick_fix/ConvertMatchToTypeOperation.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/annotator/module_attribute/issue_525.ex
testData/org/elixir_lang/annotator/module_attribute/match.ex
testData/org/elixir_lang/inspection/keyword_pair_colon_instead_of_type_operator_test_case/issue_525.ex
testData/org/elixir_lang/inspection/match_operator_instead_of_type_operator_test_case/match_operator.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java
tests/org/elixir_lang/inspection/KeywordPairColonInsteadOfTypeOperatorTestCase.java
tests/org/elixir_lang/inspection/MatchOperatorInsteadOfTypeOperatorTestCase.java

Fixes #525
* Regression test for #525
* If `:` is used instead of `::` for a type specification, mark it as an error with a Quick Fix to convert `:` to ` ::`.
* Highlight `=` operands the same as `::` operands in type specifications.
* If `=` is used instead of `::` in a type specification, mark it as an error with a Quick Fix to convert `=` to `::`.
* If a single keyword pair is used for a type spec, treat `:` as a type for `::`
* Limit variable use scope for variables "declared" in module attributes to the module attribute because the variable can't be declared there and it is really a variable usage without declaration.

Quick Fix : or = in type spec to ::

---

src/org/elixir_lang/beam/Decompiler.java
src/org/elixir_lang/beam/MacroNameArity.java
src/org/elixir_lang/beam/chunk/Exports.java
src/org/elixir_lang/beam/decompiler/Default.java
src/org/elixir_lang/beam/decompiler/InfixOperator.java
src/org/elixir_lang/beam/decompiler/MacroNameArity.java
src/org/elixir_lang/beam/decompiler/PrefixOperator.java
src/org/elixir_lang/beam/psi/BeamFileImpl.java
tests/org/elixir_lang/beam/BeamTest.java
tests/org/elixir_lang/beam/DecompilerTest.java

Fixes #581
* Macros appears before functions in decompiled `.beam` files
* Header for macro and function sections
* Add `++` to `INFIX_OPERATOR_SET`.
* Only render infix operators if arity is `2`.
* Prefix operator decompilation: `+` and `-` are both binary and unary operators.  When a unary operator they need to be wrapped in parentheses, so that the call definition clause is parsed correctly.
* Add `=~` to `INFIX_OPERATOR_SET`.
* Add `in` to `INFIX_OPERATOR_SET`.

Elixir.Kernel.beam decompilation

---

src/org/elixir_lang/beam/Decompiler.java
src/org/elixir_lang/beam/decompiler/Default.java
src/org/elixir_lang/beam/decompiler/SpecialForm.java

Fixes #594
* Some SpecialForms don't work as literals as they would be interpreted as metaprogramming, so their name needs to be wrapped as an atom to `unquote`.

Decompile SpecialForms

---

src/org/elixir_lang/annonator/Parameter.java
src/org/elixir_lang/psi/scope/Variable.java

Fixes #568
* Check children of `MultipleAliases` for variable declarations.
* Treat any variable declared in a `MultipleAliases` as invalid.

Handle MultipleAliases when resolving variables and parameters

---

.idea/runConfigurations/org_elixir_lang__ELIXIR_VERSION_1_1_1_.xml
.idea/runConfigurations/org_elixir_lang__ELIXIR_VERSION_1_3_4_.xml
.idea/runConfigurations/org_elixir_lang__ELIXIR_VERSION_1_4_0_.xml
.travis.yml
src/org/elixir_lang/annonator/Callable.java
src/org/elixir_lang/annonator/ModuleAttribute.java
src/org/elixir_lang/code_insight/lookup/element_renderer/CallDefinitionClause.java
src/org/elixir_lang/errorreport/Logger.java
src/org/elixir_lang/psi/Import.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/scope/CallDefinitionClause.java
src/org/elixir_lang/psi/scope/module/MultiResolve.java
src/org/elixir_lang/reference/Module.java
testData/org/elixir_lang/annotator/module_attribute/issue_605.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Resolves #563 
* If `multiResolve` causes a `StackOverflow` for `org.elixir_lang.annotator.Callable.visitCall`, then `catch` it and use `errorreport` logger to log the element.
* Include file path in `errorreport` excerpt
* Log element for `StackOverflow` related to `import`s
* Regression test for #605.
* Log `LookupElement#getObject` when `LookupElement#getPsiElement` is `null` to track down how it was `null` in #563.
* Skip `import Kernel` in `kernel.ex` to prevent stack overflow due to recursive `import`
* Strip all outer parentheses for left type operand, so that `(+value)` can be see as `+` operator type spec.
* Use advice from `IndexNotReadyException` documentation and check `DumbService.isDumb(Project)` before calling `StubIndex.getElements` in `Module` and …

Improve logging for CallDefinitionClause.renderElement

---

src/org/elixir_lang/reference/Callable.java

Fixes #555
Yeah, it sounds weird, but an `ElixirVariable` isn't necessarily a variable if it doesn't occur in a declaration context.  It could just be a no-parentheses function call in the wrong spot, so check the parent `PsiElement` to determine if `ElixrVariable` is a variable.

Check parent of ElixirVariable to check if a variable

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_559.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

* Regression test for #559
* Highlight parameterized type head (`maybe(t)` in `@type maybe(t)`) the same as a full type definition (`maybe(t)` in `@type maybe(t) :: t | nil`)

Highlight parameterized type head the same as full type definition

---

src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfigurationProducer.java

Fixes #562
* Only show Mix ExUnit Run in context when the module, or when the module is not a available, the project SDK is Elixir.  If there is no SDK configured, show "Mix ExUnit Run" in the menu.

Don't show Mix ExUnit Run for non-Elixir contexts

---

res/Color Settings Page Demo Text.ex

Fixes #573
* Mark `do:` as atom in demo text

Mark `do:` as atom in demo text

---

intellij-elixir.iml
src/org/elixir_lang/annonator/Callable.java

Fixes #619
Fixes #625
Fixes #626
* Annotations can only be applied to the single, active file, which belongs to the `referrer` `Callable`.  The `resolved` may be outside the file if it is a cross-file function or macro usage, in which case it's `TextRange` should not be highlighted because it is referring to offsets in a different file.

Don't highlight resolved callable if in a different file

---

CHANGELOG.md
UPGRADING.md
resources/META-INF/plugin.xml
src/org/elixir_lang/folding/Builder.java
src/org/elixir_lang/folding/ElixirFoldingSettings.java
src/org/elixir_lang/folding/OptionsProvider.java

Fixes #567
* Allow module attribute folding to be configured.
* Change to module attribute folding to off by default.

Allow module attribute folding to be configured

---

src/org/elixir_lang/code_insight/completion/provider/CallDefinitionClause.java
src/org/elixir_lang/reference/Callable.java

Fixes #546
* `CallDefinitionClause` completion provider is unexpectedly invoked both when `.` is typed, but continues to be invoked after a letter is typed after the `.`; however, once the letter is typed, the letter becomes the default prefix instead, so the prefix should only be reset to `""` when it ends in `.`.
* Disable `Callable#getVariants` unless `Unqualified` to  prevents local functions and macros being shown as completions for qualified names.

Only strip prefixMatcher when qualifier

---

resources/colorSchemes/ElixirDefault.xml

Fixes #569
* Among many other tweaks, the String color is now green, so that Atom and String are no longer close to one another, which was the original issue in #569
* `Alias` now has `underscored` effect
* `Brackets` are now greenish instead of brownish
* `Callbacks` are now a lighter blue and has `underscored` effect
* `CharList` is little lighter
* `CharToken` is dark yellow now instead of dark purple
* `Dot` is now purple instead of dark red
* `Expression Substituion Mark` is a little lighter
* `Interpolation` is now lime green
* `Kernel Macros` are a burnt orange
* `Map` is now a dark blue instead of a dark yellow
* `Operation Sign` is a little ligher
* `Paramters` are a little darker
* `Parentheses` are redder
* `Predefined` is orange instead of blue
* `Specification` is now red …

Changed default colors

---

src/org/elixir_lang/psi/scope/module_attribute/implemetation/For.java
src/org/elixir_lang/psi/scope/module_attribute/implemetation/Protocol.java
src/org/elixir_lang/reference/ModuleAttribute.java

Fixes #631
* Check if resolve results are `null` for `For.resolveResultList`
* Check if `Protocol.resolveResultList` is `null`

Check if resolve results are null in ModuleAttribute#multiresolve before addAll

---

src/org/elixir_lang/psi/scope/Variable.java

Fixes #642
* Check `match` `Call` is an `UnqualifiedNoArgumentCall`, in addition to being 0 resolved final arity, before checking if the name matches.

Check call is unqualified no argument + 0-arity

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java

Fixes #655
* Replace `assert scope.isEquivalentTo(lastParent.getParent())` with an `if` and log what `lastParent` was when condition is `false`, so root cause can be traced.

Log when scope is not last parent's parent

---

README.md

templates can be viewed as ruby to get somewhat
decent highlighting.

Document workaround for viewing Embedded Elixir

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_557.ex
testData/org/elixir_lang/annotator/module_attribute/typespec_test.exs
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #557
* Treat `::` the same as `:`  in `key:` after `when` in type specifications as it's a realistic error.
* Change `.` to `#` when referring to constants in javadocs
* Remove `@param` without descriptions
* Remove explicit type from generics when the type can be inferred.
* Check if `atNonNumericOperation` reference is non-`null` before resolving
* Swap empty branches to inverted conditions for final `else`.
* Check if `Type` `leftOperand` is `null` before using it.
* Remove empty `highlightTypesAndTypeParameterUsages(When...)`
* Remove unused `highlightTypesAndSpecificationTypeParameterDeclarations`
* Flip `equals` to eliminate need for `null` check
* Remove redundant type arguments (`<...>`)
* Change `Collections.EMPTY_SET` to `Collections.emptySet()` to prevent uncheck cast …

Treat `::` the same as `:`  in `key:` after `when` in type specifications

---

README.md

Since DataGrip (0xdbe) is no longer in early access, it's known as DataGrip.

Update 0xdbe to DataGrip.

---

resources/exunit/1.1.0/team_city_ex_unit_formatter.ex
resources/exunit/1.4.0/team_city_ex_unit_formatter.ex
resources/exunit/team_city_ex_unit_formatting.ex
src/org/elixir_lang/debugger/xdebug/ElixirXDebugProcess.java
src/org/elixir_lang/exunit/ElixirModules.java
src/org/elixir_lang/mix/runner/MixRunningState.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunningState.java
src/org/elixir_lang/sdk/ElixirSdkType.java

Fixes #676
* Use a separate formatter, one GenEvent-based and one GenServer-based, depending on whether the SDK is >= 1.4.0 as that's when GenEvent was deprecated and GenServer was preferred.

Use separate formatter for Elixir >= 1.4.0

---

resources/exunit/team_city_ex_unit_formatting.ex
src/org/elixir_lang/console/FileReferenceFilter.java

*  `TeamCityExUnitFormatting.put_event`
* Always match on `%__MODULE__{}` for state in clauses to prevent state update errors
* Match on `:suite_finished` and `:suite_started` events, so that only events added to the interface will be unknown and `IO.warn` can be used tell anyone spotting the new event to file an issue.
* `TeamCityExUnitFormatting.new` should return struct only because none of the formatters expects an `:ok` tuple.
* Fix order of `TeamCityExUnitFormatting.put_Event` catchall parameters.
* `FileReferenceFilter`
* Add `.exs` to pattern for stacktrace linking.
* Highlight only stacktrace path and line umber instead of entire line
* Better path match in stacktraces
* Only accept VirtualFile if it has a suffix matching the stacktrace's path instead of accepting the first index …

Test output improvements

---

gen/org/elixir_lang/parser/ElixirParser.java
gen/org/elixir_lang/psi/ElixirCharListLine.java
gen/org/elixir_lang/psi/ElixirInterpolatedCharListSigilLine.java
gen/org/elixir_lang/psi/ElixirInterpolatedRegexLine.java
gen/org/elixir_lang/psi/ElixirInterpolatedSigilLine.java
gen/org/elixir_lang/psi/ElixirInterpolatedStringSigilLine.java
gen/org/elixir_lang/psi/ElixirInterpolatedWordsLine.java
gen/org/elixir_lang/psi/ElixirLiteralCharListSigilLine.java
gen/org/elixir_lang/psi/ElixirLiteralRegexLine.java
gen/org/elixir_lang/psi/ElixirLiteralSigilLine.java
gen/org/elixir_lang/psi/ElixirLiteralStringSigilLine.java
gen/org/elixir_lang/psi/ElixirLiteralWordsLine.java
gen/org/elixir_lang/psi/ElixirStringLine.java
gen/org/elixir_lang/psi/impl/ElixirCharListLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirInterpolatedCharListSigilLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirInterpolatedRegexLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirInterpolatedSigilLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirInterpolatedStringSigilLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirInterpolatedWordsLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirLiteralCharListSigilLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirLiteralRegexLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirLiteralSigilLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirLiteralStringSigilLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirLiteralWordsLineImpl.java
gen/org/elixir_lang/psi/impl/ElixirStringLineImpl.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/QuoteHandler.java

Fixes #582 
* Instead of pinning position (`1` for lines or `3` for heredocs), `pin` `*_PROMOTER` token, so it's more obvious the pattern is that the promoter is pinned.
* Pin promoter for all quotes, including the previously missing `stringLine` and `charListLine`.
* Only insert closing quote if previous token was an opening quote.

Pin string and charlist to opening " or ', so that quote handler can use it for auto-insert closing

---

gen/org/elixir_lang/psi/ElixirMatchedOrOperation.java
gen/org/elixir_lang/psi/ElixirUnmatchedOrOperation.java
gen/org/elixir_lang/psi/ElixirVisitor.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/psi/call/name/Function.java
src/org/elixir_lang/psi/call/name/Module.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/operation/Or.java
src/org/elixir_lang/structure_view/element/CallDefinitionHead.java
src/org/elixir_lang/structure_view/element/Callback.java
src/org/elixir_lang/structure_view/element/modular/Module.java

Fixes #595
* On `unquote`, include argument in name of call definition clause
*  Look outside tuple containing `quote` for `enclosingMacroCall`, which allows going to [Phoenix.Template.compile's quote's defp](https://github.com/phoenixframework/phoenix/blob/v1.2.4/lib/phoenix/template.ex#L380-L392)
* Treat `Module.create` as `Modular
* `Or` interface to unify `Matched` and `Unmatched` `Or`s.
* Look at both side of `Or` operation for nested child calls for Structure view.
* Make `unquote(ARG1)` name for `getName` and indexing

Additional unquote handling

---

src/org/elixir_lang/psi/ElementDescriptionProvider.java
src/org/elixir_lang/reference/Callable.java
tests/org/elixir_lang/reference/callable/Issue436Test.java

Fixes #624
* `ElementDescription` for `ElixirVariable`
* Mark `UnqualifiedParenthesesCall`s as `call` instead of `variable`.

ElementDescription for ElixirVariable

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_632.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #632
* Mark `ElixirDecimalFloat` as error in types.
* If in a Range: "Floats aren't allowed in Ranges"
* Otherwise: "Float literals are not allowed in types.  Use float() instead".

Mark DecimalFloat as error in types

---

.gitignore
src/org/elixir_lang/annonator/Parameter.java
src/org/elixir_lang/reference/Callable.java
testData/org/elixir_lang/reference/callable/issue_659/is.ex
tests/org/elixir_lang/reference/callable/Issue659Test.java

Fixes #659
* Regression test for #659.
* Ignore `jps-*/out` directories.
* Look at parent for `isParameter` for `AtUnqualifiedBracketOperation`.
* Treat `AtUnqualifiedBracketOperation` the same as `UnqualifiedBracketOperation` for `isVariable`.

isParameter and isVariable for AtUnqualifiedBracketOperation 

---

src/org/elixir_lang/beam/StubBuilder.java
src/org/elixir_lang/beam/psi/BeamFileImpl.java
src/org/elixir_lang/beam/psi/stubs/ModuleElementType.java

Fixes #671 
* Include path in error messages from `buildFileStub`

Include path in error messages from buildFileStub

---

build.gradle
gradle.properties

Fixes #731
Fixes #686
* Update to `org.jetbrains.intellij` `0.2.15`
* Using intellij.plugins will prevent packaging intellij-erlang as a runtime dependency, which leads to duplicate templates.
* Don't use the `JPS` `type` for `jps-*` projects because their deps become incompatible with other projects.

Use intellij.plugins to get optional intellij-erlang for build

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/reference/callable/issue_687/repeated_map_value_in_match.ex
tests/org/elixir_lang/reference/callable/Issue687Test.java

Fixes #687
* Regression test for #687 
* Add missing `break`s to `case` statement in `processDeclarations(Match, ...)` that caused the logic of whether to check left, right, or both operand based on the whether the treeWalkUp came from always fell through to the `RIGHT` case, so it was only, always checking the right operand of the match and never the left operand.

Add missing breaks to case statement in `processDeclarations(Match, ...)`

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/reference/callable/issue_692/unresolved_at_top_of_file.ex
tests/org/elixir_lang/reference/callable/Issue692Test.java

Fixes #692
* Regression test for #692 
* Skip `processDeclarationsInPreviousSibling` when `lastParent` is `ElixirFile`

Skip `processDeclarationsInPreviousSibling` when `lastParent` is `ElixirFile`

---

resources/colorSchemes/ElixirDarcula.xml
resources/colorSchemes/ElixirDefault.xml

* Remove background color from sigils because it stands out really badly in the Default theme where it's black on white and while it doesn't in Darcula, it's unnecessary there because it's so close to the editor background color in Darcula.

Remove background color from sigils

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_694.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #694
* Regression test for #694 
* Treat `Alias` as miscapitalized type parameter.

Treat Alias as miscapitalized type parameter.

---

src/org/elixir_lang/annonator/ModuleAttribute.java
testData/org/elixir_lang/annotator/module_attribute/issue_699.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #699
* Regression test for #699 
* Ignore call definition clauses after `when` in type specifications as it is a common occurrence when typing a specification above a pre-existing call definition clause.

Ignore call definition clauses after `when` when typing type specificiation

---

src/org/elixir_lang/psi/stub/type/call/Stub.java

Fixes #718
* Use `THashSet` instead of the more specific `SmartHashSet` because `THashSet` allows `null` keys, which are expected for the `canonicalNameSet`.

SmartHashSet does not allow null keys

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_705__before_compile__.ex
testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_705_type_functions.ex
tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java

Fixes #705 
* Show `quote`s in list in macros in Structure View
* Look above `List` for enclosing modular macro.
* Look above `ElixirNoParenthesesManyStrictNoParenthesesExpression` for enclosing modular macro.

Look above List for enclosing modular macro

---

COLOR_SCHEME_DESIGN.md

* Remove background color from Sigil Color Scheme Design to match changes in #757.

Remove background color from Sigil Color Scheme Design

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/reference/CallDefinitionClause.java
src/org/elixir_lang/reference/Callable.java
src/org/elixir_lang/reference/Module.java
src/org/elixir_lang/reference/ModuleAttribute.java
src/org/elixir_lang/reference/resolver/CallDefinitionClause.java
src/org/elixir_lang/reference/resolver/Callable.java
src/org/elixir_lang/reference/resolver/Module.java
src/org/elixir_lang/reference/resolver/ModuleAttribute.java

Resolves #766
* References will be cached until the file containing the PSI element changes, so that results from `Callable#multiResolve`, `CallDefinitionClause#multiResolve`, `Module#multiResolve`, and `ModuleAttribute#multiResolve`, which are all the extant references, can be cached and invalidated correctly.

Cache references and references multiResolve

---

src/org/elixir_lang/debugger/xdebug/ElixirXDebugProcess.java
src/org/elixir_lang/mix/runner/MixRunConfigurationBase.java
src/org/elixir_lang/mix/runner/MixRunningState.java
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunConfiguration.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunningState.java

Fixes #709
* Use `ParameterLists` to support Path Variables in program parameters.
* Check if program parameters is blank before splitting into mix args.
* Use `ParametersList` to properly parse quote program parameters.

Check if program parameters is blank before splitting into mix args

---

src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
tests/org/elixir_lang/intellij_elixir/Quoter.java

Fixes #714
* Move `Quoter` into `test` directory, so it and its dependency on `JUnit` is only used for test compilation and runtime and not the shipped runtime.
* Fix `Quoter` warnings and format.

Move Quoter in test directory

---

src/org/elixir_lang/sdk/ElixirSdkType.java

Fixes #586
* Adjust SDK home path when `bin`, `lib,` or `src` to parent directory.
* Format `ElixirSdkType`.
* Show expected SDK home path structure when invalid. ![screen shot 2017-08-06 at 2 28 36 pm](https://user-images.githubusercontent.com/298259/29006393-5ce71dfe-7ab4-11e7-88c9-732856f6259d.png)
* Suppress invalid warnings in `ElixirSdkType`.

Better error for and adjustments for invalid SDK paths

---

src/org/elixir_lang/psi/scope/Variable.java
src/org/elixir_lang/psi/scope/variable/MultiResolve.java
testData/org/elixir_lang/reference/callable/issue_354/logger_logstash_backend.ex
tests/org/elixir_lang/reference/callable/Issue354Test.java

Fixes #354 
* Regression test for #354 
* Always check if resolution result is right operand of match.

Always check if result is right operand of match

---

src/org/elixir_lang/code_insight/completion/insert_handler/CallDefinitionClause.java

Fixes #713
* `CallDefinitionClause` `InsertHandler` always assumed there was a character after the insert location, but when inserting at the very end of the file, there isn't, which caused an `IndexOutOfBoundsException`.  Only check if the following character is not a space, `(`, or `[` when the document is longer than the tail offset to prevent the `IndexOutOfBoundsException`.  If the insertion is at the end of the file, then the `()` will always be inserted.

Check if at end of file before checking for call opener

---

build.gradle
src/org/elixir_lang/formatter/Block.java

Fixes #779
* Always install `IdeaVIM` in the gradle sandbox because it got annoying having to reinstall it when the sandbox reset.
* Delegate `ChildAttributes` to previous child when available: `Block.getChildAttributes` is used when Enter is pressed to determine the indentation and alignment.  Using the default implementation, newlines in stabs look overly indented, but there is a constant, `DELEGATE_TO_PREV_CHILD` that can be used to just use the last child's indent as long as there is one, which appears to work well for stabs (do block bodies, etc).

Delegate `ChildAttributes` to previous child when available

---

src/org/elixir_lang/mix/runner/MixRunningStateUtil.java

Fixes #603
* Format `MixRunningStateUtil` and fix warnings.
* `elixir.bat` in at least Elixir 1.5.1, will not properly parse a mix path with spaces in it on Windows even when the path has outer quotes (see elixir-lang/elixir#6455). It is not possible to use inner quotes, as you can do in cmd.exe, using the JetBrains and Java libraries hat auto-matically quote, so instead bypass the bad quoting in `elixir.bat` by doing what `elixir.bat` does: call `erl.exe` with all the SDK ebin paths added with `-pa`, then `-noshell -s elixir start_cli` to run Elixir and`-extra` to run requires (`-r`), mix and its tasks.

Expand elixir.bat to erl.exe with arguments to workaround mix quoting bug on Windows

---

src/org/elixir_lang/ElixirModules.java
src/org/elixir_lang/debugger/ElixirModules.java
src/org/elixir_lang/debugger/xdebug/ElixirXDebugProcess.java
src/org/elixir_lang/exunit/ElixirModules.java
src/org/elixir_lang/mix/runner/MixRunningState.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunningState.java

Fixes #739
* Since the process of requiring resource files is the same, `org.elixir_lang.ElixirModules` has static methods for copying resources out to a temporary directory and adding the `-r <temporary_path>` for one or more resource files to a new or existing ParametersList.  These are now shared for the Mix ExUnit and Debugger code paths.
* Format class
* `ElixirXDebugProcess`
* `MixExUnitRunningState`
* `MIxRunningState`
* The compiled `.beam` files were removed in 58e7d4a, which was before v5.1.0, but not all users had problems with using the debugger.  #739 [persisted](https://github.com/KronicDeth/intellij-elixir/issues/739#issuecomment-322032123) (as reporte by @erikreedstrom) when 6.0.0 was released; I retried reproducing on a clean VM and I got it.  I'm not sure why it worked …

Require debugger modules instead of using path prepend to compiled .beams

---

src/org/elixir_lang/debugger/xdebug/xvalue/ElixirXValueBase.java

Fixes #794
Reproduced the bug by uninstalling intellij-erlang and installing 6.1.0 from plugin repo.  Using this branch, error did not occur and debugger icons showed up.
* When #754 made `intellij-erlang` a soft-dependency, it broke the debugger's icons that referenced `ErlangIcons`, but it turns out all the icon constants were aliases to `AllIcons.Debugger` constants, so by using the `AllIcons.Debugger` icons directly, the dependency on `ErlangIcons` can be removed without the need to copy the image files into `intellij-elixir`.

Use AllIcons.Debugger directly instead of ErlangIcon aliases

---

src/org/elixir_lang/formatter/Block.java

Fixes #793
* When `do ... end` template is inserted, it did not have a previous child whose attributes to use, so it used the default, which left the cursor unindented.  To get the cursor indented by default, When the `ElementType` is `DO`, apply the `stabChildrenIndent` rules: indent normal and determine
whether to indent relative to direct parent using code style setting.

Apply stabChildrenIndent rules to DO childAttributes

---

README.md

* Add notice for debug blacklist that it uses atoms, not Aliases, so you need to qualifier module aliases with `Elixir.`.

Add notice for debug blacklist.

---

README.md
resources/debugger/lib/debug_task.ex

Auto add this prefix if string is not lowercase.

Fix Elixir prefix in debugger blacklist.

---

src/org/elixir_lang/mix/importWizard/MixProjectRootStep.form

I just saw this when setting up a new module and thought this might be the simplest PR known to man

Adding a space to import window text

---

gen/org/elixir_lang/psi/ElixirAlias.java
gen/org/elixir_lang/psi/ElixirAtom.java
gen/org/elixir_lang/psi/ElixirMatchedQualifiedAlias.java
gen/org/elixir_lang/psi/ElixirUnmatchedQualifiedAlias.java
gen/org/elixir_lang/psi/impl/ElixirAliasImpl.java
gen/org/elixir_lang/psi/impl/ElixirAtomImpl.java
gen/org/elixir_lang/psi/impl/ElixirMatchedQualifiedAliasImpl.java
gen/org/elixir_lang/psi/impl/ElixirUnmatchedQualifiedAliasImpl.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/Reference.java
src/org/elixir_lang/code_insight/completion/provider/CallDefinitionClause.java
src/org/elixir_lang/psi/Import.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/scope/Atom.java
src/org/elixir_lang/psi/scope/CallDefinitionClause.java
src/org/elixir_lang/psi/scope/atom/Variants.java
src/org/elixir_lang/psi/scope/module/Variants.java
src/org/elixir_lang/reference/Atom.java
src/org/elixir_lang/reference/Module.java
src/org/elixir_lang/reference/resolver/Atom.java
src/org/elixir_lang/reference/resolver/Module.java
src/org/elixir_lang/reference/resolver/atom/Resolvable.java
src/org/elixir_lang/reference/resolver/atom/resolvable/Exact.java
src/org/elixir_lang/reference/resolver/atom/resolvable/Pattern.java
src/org/elixir_lang/sdk/Type.java
src/org/elixir_lang/sdk/elixir/Type.java
src/org/elixir_lang/sdk/erlang_dependent/AdditionalDataConfigurable.java

Resolves #829
* All `ebin` paths in the Internal Erlang SDK will be copied to the Elixir SDK, so that they are indexed, which makes the Internal Erlang SDK modules show up in Symbol search.
* Erlang SDK modules can be completed and then functions in those modules can be completed after typing `.`.
* Atoms have References.
* Indexed atoms (from decompiled Erlang `.beams` from the Internal Erlang SDK) will be used for completing atoms as soon the atom is parseable: either after the first letter `:` or inside the quotes when making a quoted atom.
* Atoms will resolve to modules if the atom is a module name.  If the atom is quoted and contains interpolation, it will treat each interpolation as `.*` and look for regex matches to this derived potential atom name.
* Completions for functions …

Autocomplete Erlang SDK module names and functions in those modules.

---

src/org/elixir_lang/mix/runner/exunit/MixExUnitRunningState.java

Resolves #735
* Auto test for mix test case runner will automatically run tests after a change is detected in the project files, which normally happens on save, which happens when losing focus on a changed editor tab by default.

add auto test closes #735

---

src/org/elixir_lang/sdk/HomePath.java
src/org/elixir_lang/sdk/elixir/Type.java
src/org/elixir_lang/sdk/erlang/Type.java
src/org/elixir_lang/sdk/erlang_dependent/AdditionalDataConfigurable.java
src/org/elixir_lang/sdk/erlang_dependent/SdkModificatorRootTypeConsumer.java
tests/org/elixir_lang/parser_definition/ParsingTestCase.java

Fixes #847
* `AdditionalDataConfigurable` only copied the the Internal Erlang SDK Code Paths when the selection in the `ComboBox` was changed, which meant if the there was only one Erlang SDK or the user never changed the selection, the Code Paths were never copied.  To get the Code Paths copied when the Elixir SDK is first created and `setupSdkPaths` interface method is called
1. All paths are set directly on the Elixir SDK as before
2. The default Erlang SDK, which should be the one that was last created, is configured in SdkAdditionalaData
3. The Code paths from the Erlang SDK are copied to the Elixir SDK
1. If the the Erlang SDK is from intellij-elixir and does not have `ebin` directories for its Class Paths, then the Class Paths is expanded to Code Paths.

When setting up paths for Elixir SDK, setup and copy Erlang SDK paths

---

src/org/elixir_lang/sdk/elixir/Type.java

* The Code Paths from the Internal Erlang SDK were not being copied from the default Erlang SDK to the Elixir SDK when the default Erlang SDK was set during `mix test` runs, which meant that the Elixir SDK would not upgrade correctly from 6.1.1 to 6.2.0 without the user deleting the Elixir SDK and recreating it.

Configure after put default Erlang SDK

---

src/org/elixir_lang/mix/runner/MixRunningStateUtil.java

Fixes #853
Tested with Rubymine on C-S-D/alembic running `mix test`.
* Change error to say mix, elixir, or erlang path is not set instead of just mix path.
* Rewrite of `MixRunningStateUtil#setElixir` to support calling `erl` directly in IntelliJ IDEA added a check that sdk type was the Elixir SDK Type, but there was no `else` clauses to handle that there IS an SDK, but its NOT Elixir, which is the common case on all Small IDEs (like Rubymine).  To fill this gap, if the SDK is not Elixir and a Small IDE is detected, then the SDK Home from Preferences > Other Settings > Elixir External Tools > Elixir SDK > Path will be used to get the absolute path to the `elixir` (or `elixir.bat` executable and set it in the `GeneralCommandLine`.

 Use SmallIDE setting for SDK path for elixir path

---

src/org/elixir_lang/sdk/elixir/Type.java

Fixes #864 
Tested by setting up C-S-D/alembic SDK under 6.0.0, then updated to
master with changes: no errors occurred and credo issues were annotated.
* `Application#runWriteAction` MUST be run from EventDispatch thread.  This is true when run from a Run Configuration runner, but when the Credo annotator runs `runWriteAction`, it's not in an EventDispatch thread, so followed [IntelliJ Platform SDK DevGuide - General Threading Rules](https://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/general_threading_rules.html) and wrapped the `runWriteAction` in `Application#invokeAndWait`.

Wrap runWriteAction in Type in invokeAndWait

---

src/org/elixir_lang/mix/runner/MixRunningStateUtil.java

Fixes #864
Fixes #884
* Wrap `sdkModificator::commitChanges` in `invokeAndWait` `runWriteAction` in `MixRunningStateUtil#updateRoots`.

Wrap sdkModificator::commitChanges in invokeAndWAit runWriteAction

---

src/org/elixir_lang/annotator/Credo.java
src/org/elixir_lang/mix/importWizard/MixProjectRootStep.java
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
src/org/elixir_lang/sdk/ProcessOutput.java
src/org/elixir_lang/utils/ExtProcessUtil.java

Fixes #896
* Call `withCharSet(Charsets.UTF_8)` on all `GeneralCommandLines` to prevent encoding errors on Windows.

Call withCharSet(Charsets.UTF_8) on all GeneralCommandLines

---

src/org/elixir_lang/parser/ExternalRules.java

Fixes #903
*  Don't do `project instanceOf MockProjectEx` because not all IDEs, such as Rider, ship with `MockProjectEx`; instead, do a `Class#getCanonicalName()` check.

Soft-dependency for MockProjectEx

---

src/org/elixir_lang/sdk/HomePath.java

Fixes #912 
* Parse `HEAD-<SHA1>` as `0.0.<SHA1>` for sorting versions from homebrew homepath.  It will almost always be last unless there is an unknown version, which uses `0.0.0`. 
* Ensure any unparsable version sorts as `0.0.0` (`UKNOWN_VERSION`).

Parse HEAD-SHA1 as 0.0.SHA1 for sorting

---

.travis.yml
src/org/elixir_lang/annotator/Parameter.java
src/org/elixir_lang/reference/Callable.java

Fixes #929
* Look at parent of `eexTag` to resolve `fn` parameters
* Ensure functions `fn` in `eex` tags don't error by looking at `eex` element parent.
* Search above `eexTag` and `eex` to determine if variable.

Fix parameter/variable checks when in eex files

---

gen/org/elixir_lang/parser/ElixirParser.java
resources/META-INF/plugin.xml
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/Level.java
src/org/elixir_lang/eex/element_type/EmbeddedElixir.java
src/org/elixir_lang/exunit/ElixirModules.java
src/org/elixir_lang/file/LevelPropertyPusher.java
src/org/elixir_lang/mix/runner/exunit/MixExUnitRunningState.java
src/org/elixir_lang/mix/settings/MixConfigurationForm.java
src/org/elixir_lang/parser/ExternalRules.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/stub/type/File.java
src/org/elixir_lang/sdk/ProcessOutput.java
src/org/elixir_lang/sdk/elixir/Release.java
src/org/elixir_lang/sdk/elixir/Type.java
tests/org/elixir_lang/parser_definition/BracketOperationParsingTestCase.java
tests/org/elixir_lang/parser_definition/CharTokenParsingTestCase.java
tests/org/elixir_lang/parser_definition/ElixirLangElixirParsingTestCase.java
tests/org/elixir_lang/parser_definition/FunctionReferenceParsingTestCase.java
tests/org/elixir_lang/parser_definition/MatchedArrowOperationParsingTestCase.java
tests/org/elixir_lang/parser_definition/MatchedQualifiedMultipleAliasesParsingTestCase.java
tests/org/elixir_lang/parser_definition/MatchedThreeOperationParsingTestCase.java
tests/org/elixir_lang/parser_definition/NotInParsingTestCase.java
tests/org/elixir_lang/test/ElixirVersion.java

Fixes #946 
* When the SDK changes, record what `Release` of Elixir is used indirectly, using a `Level` `enum` that only cares about the major and minor version. Changing the `Level`, will mark the open files and .beam files as invalidated, so that if the SDK is changed, the stubs and code `Level` will agree, so there isn't a stub incompatibility with the PSI.

LevelPropertyPusher

---

.travis.yml
CHANGELOG.md
build.gradle
gradle.properties
resources/META-INF/changelog.html
resources/META-INF/plugin.xml
src/org/elixir_lang/beam/psi/BeamFileImpl.java
src/org/elixir_lang/code_insight/line_marker_provider/CallDefinition.java
src/org/elixir_lang/formatter/Block.java
testData/org/elixir_lang/formatting/no_parentheses_call_anonymous_function_call_alignment.ex
testData/org/elixir_lang/formatting/no_parentheses_call_multiple_anonymous_function_stab_body_alignment.ex
tests/org/elixir_lang/FormattingTest.java
tests/org/elixir_lang/mix/importWizard/MixProjectImportBuilderTest.java
tests/org/elixir_lang/parser_definition/ParsingTestCase.java

* Bump version number to 7.0.0 to account for Incompatible Changes of dropping support for IntelliJ IDEA < 2016.3 because it does not include `ReadAction.compute` and `StreamEx` used for credo performance improvements in #950.
* Add 2017.3 to build matrix
* Drop support for IntelliJ IDEA < 2016.3 because it does not include `ReadAction.compute` and `StreamEx` used for credo performance improvements in #950.

Release 7.0.0

---

src/org/elixir_lang/sdk/erlang_dependent/AdditionalDataConfigurable.java

* Check if `SdkAdditionalData` is `null` before getting `ErlangSDK` as it can be `null` in certain scenarios in Rubymine.

 Check if SdkAdditionalData is null before getting ErlangSDK

---

resources/META-INF/plugin.xml
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
src/org/elixir_lang/sdk/elixir/Type.java
src/org/elixir_lang/sdk/elixir/conversion/Converter.kt
src/org/elixir_lang/sdk/elixir/conversion/Provider.kt

Fixes #959
* `mix` runs will be faster as they will no longer check to see if the SDK is updated.
* Avoid problems with read and write locks when updating Elixir SDK on-demand by instead updating them when any project is open using a project converter.

Put default Erlang SDK and update paths in project converter

---

src/org/elixir_lang/sdk/elixir/Type.java

Fixes #961 
Fixes #962 
* https://github.com/JetBrains/intellij-community/commit/9adbba0b6fe279bcc65ad96ab7332d7bf5b59a83 added `@NotNull` to `OrderRootType.getOrderRootType`, which `JavaDocRootType.getInstance` calls, which means any Small IDE using `intellij-community` since 4 months ago, including the newest CLion cannot have `JavadocOrderRootType.getInstance` safely called.

Assume JavadocOrderRootType only exists in IntelliJ

---

src/org/elixir_lang/facet/sdks/Configurable.kt

* Path changes were not being written back to disk because the `projectSdksModel.apply()` was being called before the `editor.apply()`, which would have copied to the `editor'`s path changes to the `projectSdksModel`.

Apply ProjectSdksModel changes after Editor changes

---

src/org/elixir_lang/sdk/Type.java
src/org/elixir_lang/sdk/elixir/Type.java
src/org/elixir_lang/sdk/elixir/conversion/Converter.kt
src/org/elixir_lang/sdk/erlang/Type.java

Fixes #976 
* Use `documentionRootType` to indirectly get the documentation `OrderRootType`
in the Erlang SDK Type, so that it works in Small IDEs that have more than `CLASSES` and `SOURCES` root types installed.

Protect JavaDocRootType.getInstance in erlang/Type

---

README.md
resources/META-INF/plugin.xml

Fixes #970
* The [`credo`](https://github.com/rrrene/credo) annotator is disabled by default as numerous users find running `mix credo` in the background has a negative impact on their system performance.  If you like to try enabling the annotation, you can turn it on using the configuration.
1. Preferences > Editor > Inspections > Elixir
2. Check "Credo"
3. Click OK to save and close Preferences
If you notice a degradation the in the responsiveness of the editor, it is recommended you disable the annotator again.
1. Preferences > Editor > Inspections > Elixir
2. Uncheck "Credo"
3. Click OK to save and close Preferences

Disable credo annotator by default

---

src/org/elixir_lang/credo/inspection_tool/Local.kt

Fixes #969
* Protect from `PsiFile` being `null` in `Local` credo inspector

Protect PsiFile being null in Local credo inspector

---

jps-shared/src/org/elixir_lang/jps/model/JpsElixirSdkType.java
src/org/elixir_lang/mix/runner/MixRunningStateUtil.java
src/org/elixir_lang/sdk/elixir/Type.java

Fixes #971
* Don't add `.bat` to `mix` on Windows. `mix` is never run as an executable.  It is either run as a script to `elixir.bat` OR as an argument to `erl.exe` when `erl.exe` is running `elixir`.

Don't add `.bat` to `mix` on Windows

---

resources/META-INF/rich-platform-plugin.xml
resources/debugger/lib/debug_server.ex
resources/debugger/lib/debug_task.ex
src/org/elixir_lang/mix/importWizard/MixProjectImportBuilder.java
src/org/elixir_lang/mix/importWizard/conversion/Converter.kt
src/org/elixir_lang/mix/importWizard/conversion/ModuleSettings.kt
src/org/elixir_lang/mix/importWizard/conversion/Provider.kt
testData/org/elixir_lang/mix/import/fromRootMixExsFile/expected/14/kv.iml
testData/org/elixir_lang/mix/import/fromRootMixExsFile/expected/2017.1/kv.iml
tests/org/elixir_lang/mix/importWizard/MixProjectImportBuilderTest.java

* When importing Mix projects, don't exclude compiler output from indexing because it is needed to resolve Elixir Line Breakpoints in EEx files.
* For pre-existing Elixir modules, they will be converted to not exclude compiler output.
* Group alternatives in `erlang_module_name_patterns_to_regex` before pinning: I always forget that the `|` swallows the `^` and `$` in regexes.
* Reject vs filter accumulation got flipped when switching to `Enum.reduce` to track rejections.

Debugger fixes

---

resources/debugger/lib/debug_server.ex
resources/debugger/lib/debug_task.ex
src/org/elixir_lang/debugger/Node.java
src/org/elixir_lang/debugger/Settings.kt
src/org/elixir_lang/debugger/node/command/ReasonByUninterpretable.kt

Fixes #837
Fixes #891
Fixes #915  
Fixes #989
* Exclude known uninterpretable modules
* `Bcrypt.Base`
* `:erocksdb`
* `:lz4`
* `:re2`
* Some modules, like NIF modules, can't be loaded into the debugger. Individual modules not being debuggable shouldn't kill the debugger task, so rescue the known error and record it for later debugging of the debugger.
* Add `:` to start of Erlang module names for included debugger excludes

Don't allow uninterpretable modules to kill debugger

---

src/org/elixir_lang/beam/Beam.kt

Fixes #1029 
* Certain `.beam` files in the OTP source are purposely invalid, so ignore them when trying to parse and don't log the expected error.

Ignore test case bad-.beams

---

src/org/elixir_lang/beam/FileEditor.kt
src/org/elixir_lang/beam/chunk/code/Component.kt
src/org/elixir_lang/beam/chunk/debug_info/term/Model.kt
src/org/elixir_lang/beam/chunk/debug_info/v1/elixir_erl/v1/Component.kt
src/org/elixir_lang/beam/chunk/debug_info/v1/erl_abstract_code/abstract_code_compiler_options/Component.kt
src/org/elixir_lang/beam/chunk/elixir_documentation/Splitter.kt
src/org/elixir_lang/beam/chunk/elixir_documentation/namespace.kt

Fixes #1031 
Fixes #1039
* In order to prevent `Access is allowed from event dispatch thread only` errors when creating read-only code editor in subtabs of the BEAM Chunks editor, only create those editors when their parent tab is selected.
Affected tabs:
* Code (Elixir & Erlang)
* ExDc
* Dbgi (Elixir & Erlang)

Create BEAM Chunks tab panels only when switching to them

---

src/org/elixir_lang/UsageTypeProvider.kt
src/org/elixir_lang/psi/impl/AtUnqualifiedNoParenthesesCallImpl.kt
src/org/elixir_lang/refactoring/module_attribute/rename/Handler.kt
src/org/elixir_lang/refactoring/module_attribute/rename/Inplace.kt
src/org/elixir_lang/refactoring/module_attribute/rename/InputValidator.kt
src/org/elixir_lang/refactoring/module_attribute/rename/Processor.kt
src/org/elixir_lang/refactoring/variable/rename/Handler.kt
src/org/elixir_lang/reference/ModuleAttribute.kt
src/org/elixir_lang/reference/resolver/ModuleAttribute.kt
tests/org/elixir_lang/FindUsagesTest.kt

Fixes #1119 
* Allow module attribute declaration to resolve to itself, so that unused module attributes don't say they can't find the declaration.
* Restore rename module attributes.

Restore rename module attributes

---

src/org/elixir_lang/beam/chunk/debug_info/v1/erl_abstract_code/abstract_code_compiler_options/abstract_code/Panel.kt

* Show `...` for module name when `Dbgi` has no module name as happens for instrumented modules from `IEx.break/4`.

Show ... when Dbgi has no module name

---

src/org/elixir_lang/psi/impl/PresentationImpl.kt

Fixes #1131 
* Don't assume `callDefinitionClause` is non-`null`.

Don't assume callDefinitionClause is non-null

---

src/org/elixir_lang/psi/ElementDescriptionProvider.kt

Fixes #1135
Fixes #1139 
* Don't assume parent of list access expression is `QuotableKeywordPair`

Don't assume part of list access expression is QuotableKeywordPair

---

src/org/elixir_lang/psi/ElementDescriptionProvider.kt

Fixes #1136
Fixes #1158
Fixes #1164 
* Don't assume parent of keywords is a list

Don't assume parent of keywords is a list

---

src/org/elixir_lang/beam/chunk/code/operation/Code.kt

Resolves #1155 
* Add all OTP 21 opcodes to disassembler.  Previous opcode set was frozen prior to OTP 21 release and missed some later additions.
| number |        name        |         Added         |
|:-------|:-------------------|:----------------------|
| `160`  | `build_stacktrace` | Before OTP 21 release |
| `161`  | `raw_raise`        | Now                   |
| `162`  | `get_hd`           | Now                   |
| `163`  | `get_tl`           | Now                   |

Add all OTP 21 opcodes

---

resources/debugger/lib/intellij_elixir/debugger/server.ex
src/org/elixir_lang/debugger/node/Binding.kt

* Elixir 1.7 debugger Variables and Evaluate compatibility
* Elixir 1.7 names Erlang variables like `_<elixirVariableName>@<counter>` while Elixir 1.6 used `V<elixirVariableName>@<counter>`
* Elixir 1.7 changed `elixir_erl` record and `%Macro.Env{}`, which changed how `:elixir.quoted_to_erl` needed to be called.

Elixir 1.7 debugger compatibility

---

.travis.yml
gradle.properties
src/org/elixir_lang/distillery/State.kt
src/org/elixir_lang/iex/State.kt
src/org/elixir_lang/iex/mix/State.kt
src/org/elixir_lang/run/PendingTasksRunner.java
src/org/elixir_lang/run/TerminalExecutionConsole.java

* `TerminalExecutionConsole` itself echos input in `2018.2` and `2018.2.1`, which was introduced in
https://github.com/JetBrains/intellij-community/commit/fd7bbd0cb7f3c2a5add8872e0e6c5172be5f074a#diff-5acc2eb2e78fe52d7458d4a48b0eac9f, but it was reverted in JetBrains/intellij-community@5f4465b, so this uses that version to maintain compatibility across supported versions.
* Update `2018.2` to `2018.2.1` in build matrix.

Stop TerminalExecutionConole double echoing input in 2018.2 and 2018.2.1

---

src/org/elixir_lang/psi/impl/PsiElementImpl.kt
testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_1141.ex
tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java

Fixes #1141 
* Regression test for #1141.
* In `Phoenix.router.Helpers`, a `quote` block appears as the head of `[head
| tail]` list, so add support for search for enclosing macro call above `|`.

Check parent of Pipe for enclosing macro call

---

jps-shared/src/org/elixir_lang/jps/HomePath.java

Fixes #1143 
* In `eachEbinPath`, the ebin directories were found by iterating `<SDK_HOME_PATH>/lib` and then iterating grandchild of that, so that all paths matching `<SDK_HOME_PATH>/lib/<APP>/ebin` would be added, but for some installs from source, like SDK, there are non-OTP-app files in `<SDK_HOME_PATH>/lib`, so filter `<SDK_HOME_PATH>/lib/<APP>` to only directories.

Filter directories of homePath lib to find apps

---

src/org/elixir_lang/psi/scope/Module.kt

Fixes #1173
* `org.elixir.lang.psi.scope.Module.aliasedName(QualifiedAlias)` was already converted to use `org.elixir_lang.psi.operation.Normalized` and `org.elixir_lang.psi.infix.Normalized`, which makes it work with errors in the PSI tree, so there's no need protect with an assert and that assert would be wrong in times of errors handled by `Normalized`.

Remove assertion that a qualified alias has 3 children

---

src/org/elixir_lang/reference/module/UnaliasedName.kt

Fixes #1204
* `org.elixir_lang.reference.module.UnaliasedName.down(PsiElement)` only expects `ElixirAccessExpression` or `QualifiableAlias`, but for unexpected classes of elements, it was a simple Kotlin `TODO()`, which didn't log anything useful for enhancements.  Replace the `TODO()` with an `org.elixir_lang.errorreport.Logger.error`, so that the element's class and content can be reported when this happens again.

Improve error logging for unexpected element class unaliased name down

---

src/org/elixir_lang/ElixirModules.kt

Using paths with the Erlang CLI with backslash separators caused this error:
-r : No files matched pattern C:\Users\notriddle\AppData\Local\Temp\intellij_elixir2\exunit\1.6.0\team_city_ex_unit_formatting.ex
When the backslashes are replaced with UNIX-style forward slashes, it works correctly.

Switch out the path separator on Windows

---

resources/META-INF/plugin.xml
src/org/elixir_lang/exunit/Configuration.kt
src/org/elixir_lang/run/conversion/Converter.kt
src/org/elixir_lang/run/conversion/Provider.kt
src/org/elixir_lang/run/conversion/RunConfiguration.kt

Resolves #1218
* Convert mix and mix test run configurations to new format.

Convert mix and mix test run configurations to new format

---

src/org/elixir_lang/psi/impl/PsiElementImpl.kt
testData/org/elixir_lang/navigation/goto_symbol_contributor/issue_1228.ex
tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java

Fixes #1228 
* Regression test for #1228 
* Look above `Enum.reduce` for enclosing macro call.

Look above `Enum.reduce` for enclosing macro call

---

resources/META-INF/plugin.xml
src/org/elixir_lang/facet/configurable/Project.kt
src/org/elixir_lang/facet/external_library/conversion/Converter.kt
src/org/elixir_lang/facet/external_library/conversion/ModuleSettings.kt
src/org/elixir_lang/facet/external_library/conversion/Provider.kt
src/org/elixir_lang/facet/sdks/Configurable.kt

Fixes #1230
* Add Facet SDK as External Library to re-enable indexing.  When the External Library was removed in
4297287 in favor of a real SDK, completion for SDK `.beam` modules was lost because Small IDEs don't index SDKs, but only External Libraries, so add Application-wide External Libraries for SDKs when they are created (and update, remove on edit or delete), which are then added as a Dependency for the facet's module when the SDK is set for the Small IDE project.
* Convert old moduels with Elixir facets to also have External Library, so that users don't need to remove and add the SDKs to get the External Library.

Add Facet SDK as External Library to re-enable indexing

---

gen/org/elixir_lang/psi/ElixirIdentifier.java
gen/org/elixir_lang/psi/impl/ElixirIdentifierImpl.java
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/annotator/Callable.kt
src/org/elixir_lang/psi/impl/ElixirIdentifierImpl.kt
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/scope/Identifier.kt
src/org/elixir_lang/psi/scope/call_definition_clause/Variants.kt
src/org/elixir_lang/reference/Identifier.kt
src/org/elixir_lang/reference/resolver/Identifier.kt

Fixes #306
Fixes #1113
* Resolve unqualified bracket operation identifiers (`var` in `var[key]) to variables or `0`-arity calls.
* Fixes renames of variables not renaming usage of variables for Access lookups (i.e. `var[key]`).

Resolve unqualified bracket operation identifiers to variable and 0-arity calls

---

gradle.properties
src/org/elixir_lang/navigation/GotoSymbolContributor.kt
src/org/elixir_lang/navigation/SourcePreferredItems.kt
src/org/elixir_lang/reference/resolver/Module.kt
src/org/elixir_lang/structure_view/element/CallDefinitionClause.kt
src/org/elixir_lang/structure_view/element/CallDefinitionHead.kt
src/org/elixir_lang/structure_view/element/Quote.java
src/org/elixir_lang/structure_view/element/modular/Quote.java
tests/org/elixir_lang/navigation/GotoSymbolContributorTest.java

Fixes #667 
* Go To Symbol will no longer show redundant entries
* Call Definitions (`name/arity`) is no longer shown if the Call Definition Clause is also included.  This isn't a large loss because the `/arity` was not searchable and only part of the presentation.
* If there is a decompiled and a source version of a symbol, only the source version will be shown.
* The source Implementation will be shown and not the decompiled Module with the same fully-qualified name (`<protocol>.<for>`).
* Items will be deduped if they point to the same element, such as function clauses with default arguments because when presented they look the same even if internally one is representing `/1` and `/2`, for example.
* Go To Symbol and Go To Declaration will no longer suggest decompiled modules or …

Don't show decompiled in Go To Symbol or Declaration if source exists

---

src/org/elixir_lang/navigation/SourcePreferredItems.kt
src/org/elixir_lang/psi/scope/ResolveResultOrderedSet.kt
src/org/elixir_lang/reference/resolver/Module.kt

* Ensures that Go To Declaration for qualified calls such as `Module.function(...)` where `Module` is an alias does not return the decompiled version of `Module` when the source is available.

Prefer source over decompiled for ResolveResultOrderedSet

---

src/org/elixir_lang/psi/__MODULE__.kt

Fixes #1268
* Don't include `null` `useCall` as `__MODULE__` dependency.

Don't inclue null useCall as __MODULE__ dependency

---

src/org/elixir_lang/console/FileReferenceFilter.java

Fixes #1262
* Add `.eex` to `.ex` and `.exs` for accepted file extensions used to hyperlink files in stacktraces.

Add .eex to .ex and .exs for accepted file extensions in stacktraces

---

build.gradle
src/org/elixir_lang/psi/__module__/AliasPresentation.kt
src/org/elixir_lang/psi/impl/PresentationImpl.kt
src/org/elixir_lang/psi/impl/qualifiable_alias/ItemPresentation.kt
src/org/elixir_lang/psi/scope/Module.kt
src/org/elixir_lang/psi/scope/module/MultiResolve.kt
src/org/elixir_lang/reference/module/UnaliasedName.kt
tests/org/elixir_lang/reference/module/AsTest.java

Resolves #1266
* Resolve unaliased name when using `alias __MODULE__, as: Mod`
* Resolve usage of `Mod` in `alias __MODULE__, as Mod`
1. `Mod`
2. `__MODULE__` in `alias __MODULE__`
3. `defmodule MyModule` that is enclosing `__MODULE__`.
* Disable `ProcessCanceledException` for `runIde` gradle task, to allow for easier manual testing of completion and Go To actions during development.
* Completion of functions in current module when using `Mod.` after `alias __MODULE__, as: Mod`.
* Show more context for `alias` calls in presentations, like "Choose Declaration" pop up for Go To Declaration.
* Show resolved `__MODULE__` name (`alias MyModule`) when using `alias __MODULE__`.
* Show full `alias MyModule, as: Mod` when listing `Mod` in `alias __MODULE__, as Mod`.

alias __MODULE__ and alias M, as: N support

---

resources/exunit/.formatter.exs
resources/exunit/1.1.0/team_city_ex_unit_formatting.ex
resources/exunit/1.4.0/team_city_ex_unit_formatting.ex
resources/exunit/1.6.0/team_city_ex_unit_formatting.ex
resources/exunit/test_with_formatter.ex

Fixes #1276
* More closely match [ExUnit.CliFormatter](https://github.com/elixir-lang/elixir/blob/v1.7.3/lib/ex_unit/lib/ex_unit/cli_formatter.ex) output in Test Runner.
* Don't `inspect` ExUnit failure `reason` as `##teamcity` `message`.
* Add captured logs to failure
* Colorize test failures - including diff colorization
* `.formatter.exs` input globs would not match file paths because it was default that needed `lib` on top and not version-dependent paths used in `resources/exunit`.

More closely match ExUnit.CliFormatter output in Test Runner

---

src/org/elixir_lang/psi/scope/CallDefinitionClause.kt
testData/org/elixir_lang/reference/callable/issue_1270/nested_module_bare_words.ex
testData/org/elixir_lang/reference/callable/issue_1270/nested_module_full_qualifier.ex
testData/org/elixir_lang/reference/callable/issue_1270/nested_module_relative_qualifier.ex
testData/org/elixir_lang/reference/callable/issue_1270/outer_module_bare_words.ex
testData/org/elixir_lang/reference/callable/issue_1270/outer_module_relative_qualifier.ex
tests/org/elixir_lang/reference/callable/Issue1270Test.kt

Fixes #1270
* Regression test for #1270.
* When finding a `defmodule`, check that it is an ancestor of the entrance of the `ResolveState`, so that nested sibling modules are not scanned for potential call definition clauses, but only the outer module of the entrance.

Only look in outer nested module for callable completion

---

resources/exunit/1.1.0/team_city_ex_unit_formatting.ex
resources/exunit/1.4.0/team_city_ex_unit_formatting.ex
resources/exunit/1.6.0/team_city_ex_unit_formatting.ex

Fixes #1303
* Fix unused variables in `TeamCityExUnitFormatting`
* `reason` was completely unused.
* `details` should have been used.

Fix unused variables in TeamCityExUnitFormatting

---

src/org/elixir_lang/exunit/MixOutputToGeneralTestEventsConverter.java
src/org/elixir_lang/mix/runner/Status.java

Fixes #1023
* `flushBufferBeforeTerminating` was deprecated and in newer IntelliJ the
call to `processStatuses` does not occur unless `flushBufferOnProcessTermination` is also overridden.
* Treat `== Compilation error` in `STDOUT` as `ERROR` for ExUnit reporter
* Convert `(CompileError)` of a test file to test failure.  The "Test framework quit unexpectedly" is converted to a failed run with a single test with the compilation error as the failure message.

Convert CompileError in test file to test failure

---

gradle.properties
src/org/elixir_lang/psi/stub/index/AllName.java
src/org/elixir_lang/structure_view/element/modular/Module.kt

Fixes #1301
* Don't treat redefinition of `defmodule` macro as module definition (as occurs in @bitwalker's distillery' `Mix.Tasks.Release.Init.MixMock`
* Bump `AllName` `VERSION` to re-index and drop bad call definition head from #1301.

Don't treat redefinition of defmodule as module definition in distillery

---

src/org/elixir_lang/mix/runner/Status.java

* Don't log compilation errors as test failures unless a test has started.   Test name being called `mix test` does not work, so log those compilation errors as normal build messages instead.

Don't log test failures unless a test has started

---

src/org/elixir_lang/debugger/Settings.kt

Fixes #1307
* Don't interpret `:crypto` by default: `:crypto` includes NIFs that can't be reloaded and so kills the debugger.

Don't interpret :crypto by default

---

src/org/elixir_lang/code_insight/completion/provider/CallDefinitionClause.kt

Fixes #1309
* Protect from `null` `containingFile` for modular names during completion.

Protect from null containingFile for modular names during completion

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/stub/call/Deserialized.java

Fixes #1320
* Log `nameSet` when it reaches suspect size (`10`) to allow triaging if it is a real bug or just something with a lot of valid names.
* Fix inverted condition around when to warn and when to error and use `readAheadLength`.

Log nameSet when it reaches suspect size

---

README.md

Fixes #1326
* Fix deadlinks to Run Configurations, which broke when section was renamed Run/Debug Configurations and auto-anchor changed name.

Fix deadlinks to Run Configurations

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/watcher/Resolution.kt

Fixes #1335
* Wrap `packagePisToDepSet` in read action because checking the validity of the dependencies requires a read action.

Wrap packagePsiFileToDepSet in read action

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/DepsWatcher.kt
src/org/elixir_lang/mix/Dep.kt
src/org/elixir_lang/mix/Watcher.kt
src/org/elixir_lang/mix/watcher/Resolution.kt

Fixes #1343
*  Use `:path` for deps for paths external to project.  Unfortunately, even though they show up in the Project Structure, only `ebin` directories are shown as it is restricted to those marked as `CLASSES` and the `:path` `lib` is a `SOURCES`.

Use :path for deps for paths external to project

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/Dep.kt

* Ignore `:ref` when finding path to dep.

Ignore `:ref` when finding path to dep

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/QuotableImpl.kt

Fixes #1381
* Wrap `UnqualifiedNoArgumentCall.quote` `identifier.text` in `runReadAction`.

Wrap UnqualifiedNoArgumentCall identifier.text in runReadAction

---

CONTRIBUTING.md

Just some very minor typo fixes in the documentation: the names of `runIde` and `verification` were misspelled in `CONTRIBUTING.md`.

Fix the names of the Gradle tasks in contribution guidelines

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/annotator/ModuleAttribute.java

EEx files do not have enough context to correctly recognize `@conn` and other attributes used in EEx files. Fixes issue #924.
The condition in the `if` statement checks if the file we're currently in has EEx enabled. If it does, then we skip applying the annotator to the element. I tested this both with the unit tests and interactively, and it works as intended.

Prevent the module attribute annotator from running in EEx files.

---

src/org/elixir_lang/psi/stub/call/Deserialized.java

Fixes #1436
* Increase suspect `nameSet` size to `15` to support [`geo`](https://hex.pm/packages/geo).  `geo` has [13 `String.Chars` implementations](https://hexdocs.pm/geo/3.1.0/api-reference.html).

Increase suspect nameSet size to 15 to support geo

---

CHANGELOG.md
resources/META-INF/changelog.html
resources/fileTemplates/internal/ESpec.exs.ft
resources/fileTemplates/internal/ESpec.exs.html

Fixes #1427
* Adding missing ESpec template.  When reviewing #1410 I missed that the template wasn't in `resources`. 🤦‍♂️

Add missing ESpec template

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/Dep.kt

Fixes #1431
* Ignore `targets` when calculating `Dep` path.

Ignore targets when calculating Dep path

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/Dep.kt

Fixes #1424
* Ignore `organization` when calculating `Dep` path.

Ignore organization when calculating Dep path

---

gen/org/elixir_lang/psi/ElixirAlias.java
gen/org/elixir_lang/psi/ElixirMatchedQualifiedAlias.java
gen/org/elixir_lang/psi/ElixirUnmatchedQualifiedAlias.java
gen/org/elixir_lang/psi/impl/ElixirAliasImpl.java
gen/org/elixir_lang/psi/impl/ElixirMatchedQualifiedAliasImpl.java
gen/org/elixir_lang/psi/impl/ElixirUnmatchedQualifiedAliasImpl.java
src/org/elixir_lang/psi/impl/ElixirPsiImplUtil.java
src/org/elixir_lang/psi/impl/QualifiableAliasImpl.kt
src/org/elixir_lang/psi/scope/module/MultiResolve.kt
src/org/elixir_lang/reference/Module.kt
src/org/elixir_lang/reference/resolver/Module.kt

Fixes #1416
* Always use `containingFile` for `QualifiableAlias` `maxScope` for `getReference`.  Prevents cache capturing `maxScope`, which can vary based on invocation.

Always use containingFile for QualifiableAlias maxScope

---

.travis.yml
CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/code_insight/line_marker_provider/CallDefinition.kt
src/org/elixir_lang/mix/project/DirectoryConfigurator.kt
src/org/elixir_lang/sdk/ProcessOutput.java

* Use reflections to allow saving settings when creating the projects before in 2018.3 and 2019.1 even though the API changed.
* Create new project before attaching it in Small IDEs.
When attaching a directory to a project during startup, saving is disallowed, so the attached directory only has a `workspace.xml` in its `.idea` when the attach is attempted.  Attaching requires the `.idea/*.iml` Module file, so the attaching fails, saying the directory is an unsupported format.
Experimentation showed that manually attaching the directory also did not work, but opening the directory in a separate window, then opening and attaching it again would make the directory have the full project files.  To mimic this manual process:
1. The internals of `doOpenProject` are copied
2. A save of the …

Only attach full projects if the IDE can attach full projects

---

CHANGELOG.md
resources/META-INF/changelog.html
resources/debugger/lib/intellij_elixir/debugger/server.ex

Tested using `eex_test_umbrella` and evaluating parameters using Elixir 1.7.4 and 1.8.1.
* Elixir 1.8 made `:elixir.quoted_to_erl/3` private, so in Elixir 1.8+, the debugger needs to inline the private version to maintain < 1.8 and >= 1.8 compatibility.
* Reformat debugger for Elixir 1.8

1.8 debugger

---

src/org/elixir_lang/espec/MixOutputToGeneralTestEventsConverter.java
src/org/elixir_lang/exunit/MixOutputToGeneralTestEventsConverter.java

Constructor argument does not have to same meaning as OutputLineSplitter.

Don't pass argument to OutputEventSplitter

---

.travis.yml
build.gradle
gradle.properties

* Update gradle plugins
* `gradle-intellij-plugin` (`org.jetbrains.intellij`) to `0.4.10`
* `org.jetbrains.kotlin.jvm` to `1.3.50`
* `de.undercrouch.download` to `4.0.0`
* Update IDEA version in builds
* `2019.2` -> `2019.2.2`
* Update gradle intellij plugin to fix `runIde` on newer macOS.

Plugin updates

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/iex/Mix.kt

Hi, I changed the mix path on IEx Mix Run/Debug configuration to use absolute path instead of relative path, which was causing issues with asdf. The change is similar to what's already in  [Mix.kt](https://github.com/KronicDeth/intellij-elixir/blob/b80bba9ae0a576770f992b97800ea14d937f7547/src/org/elixir_lang/Mix.kt#L31-L34)
Fixes:
With [asdf](https://github.com/asdf-vm/asdf), launching IEx Mix Run/Debug Configuration will load `~/.asdf/shims/mix` and throw following error.
```
** (SyntaxError) /Users/chitacan/.asdf/shims/mix:11: syntax error before: '.'
(elixir) lib/code.ex:813: Code.require_file/2
```

Use absolute path for IEx Mix Run/Debug configuration.

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/beam/chunk/code/operation/Code.kt
src/org/elixir_lang/beam/chunk/code/operation/code/Argument.kt

Fixes #1593
* Add OTP 22 and 23 opcodes to Code BEAM Chunk Viewer
* `put_tuple/2`
* `bs_get_tail/3`
* `bs_start_match3/4`
* `bs_get_position/3`
* `bs_set_position/2`
* `swap/2`

Add OTP 22 and 23 opcodes

---

src/org/elixir_lang/sdk/ProcessOutput.java

When I setup the Elixir SDK, I get Unknown Elixir version.
The idea.log says:
> java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
> 	at com.intellij.execution.process.BaseProcessHandler.<init>(BaseProcessHandler.java:34)
> 	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:32)
> 	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:151)
> 	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:35)
> 	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:28)
> 	at org.elixir_lang.sdk.ProcessOutput.execute(ProcessOutput.java:95)
> 	at org.elixir_lang.sdk.ProcessOutput.getProcessOutput(ProcessOutput.java:85)
> 	at …

Fix "Unknown Elixir version" in settings

---

resources/debugger/lib/intellij_elixir/debugger/server.ex

* Fix debugger evaluator for Elixir >= 1.9.2. Ports elixir-lang/elixir@7002554a478f4c99dc4b63786a13cc7dca67799d.

Fix debugger evaluator for >= 1.9.2

---

.github/workflows/test.yml
CHANGELOG.md
build.gradle
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/Icons.kt
src/org/elixir_lang/debugger/StackFrame.kt
src/org/elixir_lang/mix/DepGatherer.kt
src/org/elixir_lang/mix/project/DirectoryConfigurator.kt
src/org/elixir_lang/psi/impl/QuotableImpl.kt
src/org/elixir_lang/rebar3/DepGatherer.kt

Change old references to new that are recommended by documentation. 
Happy Easter Eggs
* Update build to IntelliJ IDEA 2020.1
* JetBrains IDEs 2020.1 compatibility
* Change obsolete references to `AllocIcons` in `Icons` to new ones in `AlllIcons` that are recommended in documentation.
* Update to `@NotNull` annotation on `PsiElementVisitor`
* `DepGatherer`
* `QuotableImpl.quote`

Fix Icon issue for IntelliJ 2020.1

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/project/_import/Provider.java

Fixes #1634
* Get `ProjectImportProvider` builder in `doGetBuilder` instead of constructor.
Fixes use of deprecated constructor dependency injection that is incompatible with dynamic, injectable plugins in 2020.1.
```
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is
used to get org.elixir_lang.mix.project._import.Builder(
requestorClass=org.elixir_lang.mix.project._import.Provider,
requestorConstructor=protected org.elixir_lang.mix.project._import.Provider(org.elixir_lang.mix.project._import.Builder)
).
Probably constructor should be marked as NonInjectable. [Plugin: org.elixir_lang]
```

Get ProjectImportProvider builder in doGetBuilder instead of constructor

---

src/org/elixir_lang/sdk/elixir/Type.java

* Don't check for `isUnitTestMode` in `org.elixir_lang.sdk.elixir.Type` initializers because it makes tests flaky.

Don't check for isUnitTestMode in org.elixir_lang.sdk.elixir.Type initializers

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/QuotableKeywordPairImpl.kt
src/org/elixir_lang/reference/module/UnaliasedName.kt

Fixes #1611
* Only require at least the number of children to safely get a specific child instead of exact number to allow getting prefix children when there are grammatical errors.

Only require at least instead of exact number of children

---

CHANGELOG.md
resources/META-INF/changelog.html
resources/META-INF/plugin.xml

This PR provides basic support for formatting EEx files.
By basic, I mean that the underlying language is formatted, but the Elixir constructs are not taken into account.
For example, following snippet of HTML:
```eex
<html>
<body>
<div>
<%= if true do %>
<p>Hallo</p>
<% end %>
<p>Test</p>
</div></body></html>
```
will be formatted as:
```eex
<html>
<body>
<div>
<%= if true do %>
<p>Hallo</p>
<% end %>
<p>Test</p>
</div>
</body>
</html>
```
As you can see, the content inside the `if` was not intented. I haven't found an easy way to support this, short of writing a much more complex formatter. As such, I think enabling this will not result in perfect formatting, but it is better then the current situation. Relevant issue is #1594.

Use default formatter for EEx files

---

CHANGELOG.md
resources/META-INF/changelog.html
resources/META-INF/plugin.xml
src/org/elixir_lang/exunit/TestLineMarkerProvider.kt
src/org/elixir_lang/exunit/configuration/Producer.kt
src/org/elixir_lang/mix/TestFinder.java

- This PR adds the "run" icons in the gutter for tests:
- There are also some small clean-ups in related code.
For the run icons:
- They use the existing run actions, same as when you right-click.
- They only appear of the file is a test file (suffix _test.exs and in a map marked as tests in the project structure)
- I have no idea how one should write a test for this stuff, so I didn't (I'm fairly new to Intellij SDK stuff)
- I hardcoded "test", "describe", "doctest" and "defmodule". I don't know if it would be better to dynamically determine these, but that would be fairly hard I think.
I have been using this some time in a personal fork and it seems to work pretty well.
Fixes #688.

Adds Run icon in gutter next to ExUnit tests

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/debugger/Modules.kt

Fixes #1347
* On Windows, the `file.path` to the debugger server files has `\`, but they aren't escaped.  Therefore, replace them with escaped version, `\\` to fix debugging on Windows, but leave Linux and macOS unaffected.

Double escape \ in debugger file paths

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/QuoteHandler.java

Fixes #1865
* Protect against `IndexOutOfBounds` from `highlighterIterator` in `QuoteHandler`.

Protect against IndexOutOfBounds from highlighterIterator

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/DepsWatcher.kt
src/org/elixir_lang/mix/Project.kt
src/org/elixir_lang/mix/Watcher.kt
src/org/elixir_lang/mix/project/DirectoryConfigurator.kt

Fixes #1871
* Fix missed references to `DepsWatcher` as project component
`DepsWatcher` was converted to a Project Listener in #1844 to support installing the plugin from the Marketplace without reloading, but some references to `DepsWatcher` were still trying to get its instance for project using `project.getComponent()`, which would now return `null`.

Fix missed references to DepsWatcher as project component

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html

Fixes #1879
* Target Java 1.8 for JPS compatibility
JPS (JetBrains Project System) is the API used to allow External Builders, like `mix` to build projects.

Target Java 1.8 for JPS compatibility

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/beam/Decompiler.java
testData/org/elixir_lang/beam/decompiler/Docs/Elixir.Kernel.SpecialForms.ex
testData/org/elixir_lang/beam/decompiler/Docs/Elixir.Kernel.ex
tests/org/elixir_lang/beam/DecompilerTest.java

* Fix capitalization of `Docs` `@moduledoc`
`@moduleDoc` -> `@moduledoc`

Fix capitalization of Docs @moduledoc

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/eex/file/Type.kt

* Simplify `onlyTemplateDateFileType`
* Use `VirtualFile#fileType` instead of EEx Type::INSTANCE when looking up extensions.
Since LEEx file `Type` is a subclass of EEx's file `Type`, it calls `templateDataFileTypeSet` in EEx's `Type`, but `templateDataFileTypeSet` uses `INSTANCE` from EEx.  By using the `VirtualFile#fileType` instead, it will properly be EEx or LEEx based on the actual file extension and then it can be used to strip that off and find the DataTemplateLanguage, such as `HTMLLanguage` for `.html.leex`.

Fix associating HTML as DataTemplateLanguage for *.html.leex

---

.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/call/CallImpl.kt

Fixes #1876
* Log `PsiElement` if `Call#finalArguments` contain a `null`.
* Don't return null left or right infix operands in `primaryArguments`
`operation.infix.Normalized.leftOperand` and `.rightOperand` ensures that `PsiErrorElement` is not returned: they can return `null` when there is no left or right operand.  `Infix.primaryArguments` was not taking this into account and so could return a `null` as one of the `primaryArguments`, which broke `Call.finalArguments`.

Don't return null left or right infix operands in `Infix.primaryArguments`

---

resources/META-INF/description.html

fix golang IDE name in description.
readme was fixed  https://github.com/KronicDeth/intellij-elixir/pull/999, but description is not.

fix word in description.html (goland)

---

CHANGELOG.md
build.gradle
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/UsageTypeProvider.kt
src/org/elixir_lang/beam/psi/BeamFileImpl.kt
src/org/elixir_lang/beam/psi/stubs/ModuleElementType.java
src/org/elixir_lang/beam/psi/stubs/ModuleStubElementType.java
src/org/elixir_lang/beam/psi/stubs/ModuleStubElementTypes.java
src/org/elixir_lang/errorreport/Submitter.kt
src/org/elixir_lang/file/LevelPropertyPusher.java
src/org/elixir_lang/mix/project/DirectoryConfigurator.kt
src/org/elixir_lang/psi/impl/PresentationImpl.kt
src/org/elixir_lang/sdk/elixir/Type.kt
tests/org/elixir_lang/beam/DecompilerTest.java
tests/org/elixir_lang/parser_definition/ParsingTestCase.java

* Updates
* IntelliJ IDEA build version to 2021.1.2
* Update `ParsingTestCase` to latest APIs.
* Gradle plugins
* intellij 1.0
* kotlin.jvm 1.5.10 
* Configure `runPluginVerifier`
* `updateSinceUntilBuild` to prevent breaking in future IDEs.
* Check if modules loaded before using `findModuleForPsiElement`.
* Use `BasePlatformTestCase` instead of `LightCodeInsightTestCase` because `LightCodeInsightTestCase` is deprecated.

Update IntelliJ IDEA version to 2021.1.2

---

CHANGELOG.md
gen/org/elixir_lang/psi/scope/Type.kt
resources/META-INF/changelog.html

Fixes #1979
* Log element in psi.scope.Type instead of using `TODO()`
Error will still be reported, but there will be enough information to triage and since `true` is returned now it won't stop the type resolving from working.

Log element in psi.scope.Type instead of TODO()

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/Dep.kt

Fixes #1498
Fixes #1983
* Add missing mix deps options to non-path influencing lists:
* env
* manager
* repo
* sparse
* submodules
* system_env

Add missing mix deps options to non-path influencing lists

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/PsiNamedElementImpl.kt

Fixes #1975
* Run `QualifiedAlias#text` in `runReadAction` for `QualifiedAlias#name`.

Run QUalifiedAlias#text in runReadAction for QualifiedAlias#name

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/beam/FileEditor.kt
src/org/elixir_lang/beam/chunk/code/Component.kt
src/org/elixir_lang/beam/chunk/debug_info/term/Model.kt
src/org/elixir_lang/beam/chunk/debug_info/v1/elixir_erl/v1/Component.kt
src/org/elixir_lang/beam/chunk/debug_info/v1/erl_abstract_code/abstract_code_compiler_options/Component.kt
src/org/elixir_lang/beam/chunk/elixir_documentation/Splitter.kt
src/org/elixir_lang/beam/chunk/elixir_documentation/namespace.kt

Fixes #1918
* Implement `beam.FileEditor#getFile` to fix `DeprecatedMethodException` as the default implementation is now deprecated and requires an explicit implementation.
* Use `TabbedPaneWrapper.AsJBTabs` instead of `JBTabbedPane` for "BEAM Chunks" tabs.
I'm not sure why `JBTabbedPane` stopped showing its labels sometime in the 2020.X IDE version series, but by debugging when "BEAM Chunks" name was retrieved I found that the bottom tabs used `TabbedPaneWrapper.asJBTabs`.  Using that, the labels reappeared.

Fix BEAM Chunks tab labels not displaying

---

CHANGELOG.md
gen/org/elixir_lang/psi/scope/module/Variants.kt
resources/META-INF/changelog.html

Fixes #1998
* Don't require Alias qualifier to be a `PsiNamedElement`
It can be an `ElixirAtom` and getting the reference will still work.

Don't require Alias qualifier to be a PsiNamedElement

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/navigation/SourcePreferredItems.kt

Fixes #1901
* `Any.isDecompiled` for `CallDefinitionHead`.

Any.isDecompiled for CallDefinitionHead

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/annotator/ModuleAttribute.kt
src/org/elixir_lang/psi/call/name/Function.java
testData/org/elixir_lang/annotator/module_attribute/issue_2198.ex
tests/org/elixir_lang/annotator/ModuleAttributeTest.java

Fixes #2198
* Regression test  for #2198.
* Stop highlighting types when `unquote_splicing/1` is reached.
`unquote_splicing` is being used to splat arguments or fields of a struct into the type.  The arguments to `unquote_splicing` are normal calls or variables, not types.

Stop highlighting types when `unquote_splicing/1` is reached

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/structure_view/element/CallDefinitionClause.kt

Fixes #2009
* `CallDefinitionClause.time/1`
* Mark guards as runtime.
* Mark anything unknown as runtime too.
* Log unknown calls.

Add guards to CallDefinitionClause.time/1

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/PresentationImpl.kt

Fixes #2011
* Check if `Call` `isValid` before using `containingFile` for `locationString`.

Check if Call isValid before using containingFile for locationString

---

CHANGELOG.md
gen/org/elixir_lang/psi/scope/variable/MultiResolve.kt
resources/META-INF/changelog.html
src/org/elixir_lang/reference/resolver/Callable.kt
src/org/elixir_lang/reference/resolver/Module.kt

* Take `resolveInScope` only if at least one valid
Checking only for an empty collection allowed any prefixes in the scope to override exact matches in anywhere indexed, which meant that `Ecto` in `defmodule Ecto.Adapter do` resolved to itself instead of the exact `defmodule Ecto do`.

Take resolveInScope only if at least one valid

---

CHANGELOG.md
gen/org/elixir_lang/psi/ElixirVisitor.java
resources/META-INF/changelog.html
testData/org/elixir_lang/psi/elixir_visitor/autogenerate_test.exs
tests/org/elixir_lang/psi/ElixirVisitorTest.kt

* When regenerating the parser, `ElixirVisitor` is also regenerated.  When it was regenerated it lost the bug fix for `#visitLiteralSigileLine` calling itself.  Added a regression test, so that this can't happen again.

Restore fix for ElixirVisitor#visitLiteralSigilLine infinite recursion

---

CHANGELOG.md
gen/org/elixir_lang/psi/scope/call_definition_clause/MultiResolve.kt
gen/org/elixir_lang/psi/scope/call_definition_clause/Variants.kt
resources/META-INF/changelog.html
src/org/elixir_lang/code_insight/lookup/element_renderer/Delegation.kt
src/org/elixir_lang/code_insight/lookup/element_renderer/EExFunctionFrom.kt
src/org/elixir_lang/code_insight/lookup/element_renderer/LookupElementPresentationExt.kt
src/org/elixir_lang/code_insight/lookup/element_renderer/exception/CallDefinitionClause.kt
src/org/elixir_lang/code_insight/lookup/element_renderer/mix/generator/EmbedTemplate.kt
src/org/elixir_lang/code_insight/lookup/element_renderer/mix/generator/EmbedText.kt
src/org/elixir_lang/psi/Exception.kt
src/org/elixir_lang/structure_view/element/Delegation.kt
src/org/elixir_lang/structure_view/element/EExFunctionFrom.kt
src/org/elixir_lang/structure_view/element/EExFunctionFromHead.kt
src/org/elixir_lang/structure_view/element/modular/Module.kt
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/defdelegate.ex
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/eex.ex
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/eex_function.ex
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/exception.ex
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/mix_generator.ex
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/mix_generator_embed.ex
testData/org/elixir_lang/code_insight/completion/contributor/call_definition_clause/to.ex
tests/org/elixir_lang/code_insight/completion/contributor/CallDefinitionClauseTest.java

Fixes #2122
* Structure View for `EEx.function_from_(file|string)`
* Variants (completion) for functions declared by special macros.
* Functions defined by `EEx.function_from_(file|string)`
* `exception/1` and `message/1` defined by `defexception`
* `*_text/0` and `*_template(assigns)` functions defined by `Mix.Generator.embed_text` and `Mix.Generator.embed_template`.
* Implement completion for functions declared with `defdelegate`.
* Fix `LookupElementPresentation.putItemPresentation` `addTailText`.
Only append suffix of `presentableText` if it is prefixed by `itemText`.

Variants (completion) of defdelegate defined functions

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/QualifiableAliasImpl.kt

Fixes #2344
* Stop look for qualifier at curly braces for `%{Alias}`

Stop look for qualifier at curly braces for %{}

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/exunit/configuration/Producer.kt

Fixes #2384
* Protect ExUnit configuration `Producer` from `ElixirFile` without `VirtualFile`.

Protect ExUnit configuration Producer from ElixirFile without VirtualFile

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/annotator/ModuleAttribute.kt
src/org/elixir_lang/annotator/Textual.kt

* Don't highlight `Quote` or `Sigil` as normal text if part of documentation.
Since the annotators will run in arbitrary order, the `Textual` annotator has to avoid annotating the same nodes as the `ModuleAttribute` annotator or the colors can get interleaved.

Don't highlight Quote or Sigil as normal text if part of documentation

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/__module__/Resolver.kt

Fixes #2442
* Put `ENTRANCE` and Initial Visited Element in `__module__.Resolver`.

Put ENTRANCE and Initiali Visited Element in __module__.Resolver

---

CHANGELOG.md
gen/org/elixir_lang/psi/ElixirAtom.java
gen/org/elixir_lang/psi/impl/ElixirAtomImpl.java
resources/META-INF/changelog.html
src/org/elixir_lang/Elixir.bnf
src/org/elixir_lang/reference/module/UnaliasedName.kt
testData/org/elixir_lang/reference/module/as/issue_2446/asd_xS@ps.ex
testData/org/elixir_lang/reference/module/as/issue_2446/index.ex
tests/org/elixir_lang/reference/module/as/Issue2446Test.kt

* Regression test for #2446
* Fix `UnaliasedName.unaliasedName` for atoms.
* Restore `ElixirAtom#getName`
Lost when parser was regenerated when Elixir <= 1.6 support was dropped in 679a9689cfe097018b9baa4e894d4550a84d7aac.

Fix resolving Erlang modules aliased with as

---

CHANGELOG.md
build.gradle
resources/META-INF/changelog.html
src/org/elixir_lang/facet/configurable/Project.kt
src/org/elixir_lang/notification/setup_sdk/Listener.kt
src/org/elixir_lang/notification/setup_sdk/Provider.kt
src/org/elixir_lang/sdk/erlang_dependent/SdkAdditionalData.java

* Expand `untilBuild` to cover PATCH releases of 2022.1.
* Don't use ElixirModuleType to check if it is available.
It will not load in IDEs that lack `JavaModuleBuilder`, which is why I was hard coding the ran previously.
* Don't use `XmlSerializer` as equivalent of `DefaultJDOMExternalizer`
The `DefaultJDOMExternalizer` method calls weren't writing anything and the explicit attribute value accesses were, so it is more correct to just remove the original deprecated calls.

Fix Deprecate Warning fixes that broke small IDEs

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt

Fixes #2564
* Protect from `null` `containingFile` when fetching docs.

Protect from `null` `containingFile` when fetching docs

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/sdk/elixir/Type.kt

Fixes #2582
* Catch `AlreadyDisposedException` when trying to find module for PsiElement in `mostSpecificSdk`.
* Check if the project`is disposed before using it to get module for `PsiElement`.

Catch AlreadyDisposedException when trying to find module for PsiElement

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/annotator/ModuleAttribute.kt

Fixes #2583
* Ignore `()` as a type parameter as it occurs during typing.

Ignore `()` as a type parameter as it occurs during typing.

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/code_insight/lookup/element_renderer/Variable.java

Fixes #2589
* Default the variable color if the specific type foreground is `null`

Default to the variable color if the specific type foreground is null

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/scope/Type.kt

Fixes #2596
* Look above `CallDefinitionImpl` for `Type` scope processing
It should go up to the `ModuleImpl` to find the `TypeDefinitionImpl`.

Look above CallDefinitionImpl for Type scope processing

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/scope/Type.kt

Fixes #2610
* Look above `<variable>.<tuple>` for `ancestorTypeSpec`.
* Look above `<tuple>` after `<variable>.` for `ancestorTypeSpec`.

Fix ancestorTypeSpec when typing <variable>.<tuple>

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/annotator/ModuleAttribute.kt

Fixes #2626
* Ignore invalid format that occur while user is typing when highlighting types
* `@type name :: String.()`
* `@type String.()`
* `@type S`

Ignore dot calls during user typing when highlighting types

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/facet/configurable/Project.kt

Fixes #2656
* Restore Project configuration for Small IDEs.
I dropped an `!` when converting from `equals` to `==` when fixing the deprecation warnings, which made the Project SDK selection _only_ be **HIDDEN** where it needed to be **SHOWN**.

Restore Project configuration for Small IDEs 

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/annotator/Callable.kt

Fixes #2661
* Highlight `CallDefinitionImpl` references as predefined if resolved `CallDefinitionImpl` is in `Kernel` or `Kernel.SpecialForms`.
Fixes highlighting `def` and other defined when using SDKs without source like Homebrew after the delayed-decompilation fixes from 12.2.1.  Now source-less (Homebrew) and SDKs with sources (ASDF) will both be able to highlight predefineds.

Highlight CallDefinitionImpl as predefined if it is in Kernel or Kernel.SpecialForms

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/UsageTargetProvider.kt

Fixes #2694
* Restrict `UsageTargetProvider` to `ElixirFile`s
Without this restriction, it tries to run when developing the plugin itself and breaks Kotlin syntax highlighting.

Restrict UsageTargetProvider to ElixirFiles

---

CHANGELOG.md
resources/META-INF/changelog.html
resources/debugger/lib/intellij_elixir/debugger/server.ex
src/org/elixir_lang/espec/Configuration.kt
src/org/elixir_lang/exunit/Configuration.kt

Fixes #2488
Fixes #2696
* Support Elixir 1.13.0 in debugger.
* Fix environment not being passed to debug runs of ESpec and ExUnit Run Configurations.
The `env` from the `Configuration` was dropped because a local `env` was created to set `MIX_ENV` `true`.

Support Debugger in Elixir 1.13.0

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/beam/psi/impl/ModuleImpl.kt
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt
src/org/elixir_lang/psi/scope/CallDefinitionClause.kt

Fixes #2704
* Fix Go To Definition for function in compiled modules.
When switching over to delayed decompilation, `ModuleImpl` did not have `processDeclaration` overloadded, so the `PsiScopeProcessor` was never called on it and so the `CallDefinitionClause` scope processor did not check the `ModuleImpl#callDefinitons`.
* Implement Deprecated metadata handling for docs from BEAM files.

Implement Deprecated metadata handling for docs from BEAM files

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/Elixir.kt

Fixes #2706
* Don't assume Elixir `SDK` `sdkAdditionalData` is non-`null`.

Don't assume Elixir SDK sdkAdditionalData is non-null

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/elixir/configuration/Editor.java
src/org/elixir_lang/erl/configuration/Editor.java
src/org/elixir_lang/espec/configuration/Editor.java
src/org/elixir_lang/exunit/configuration/Editor.java
src/org/elixir_lang/iex/configuration/Editor.java
src/org/elixir_lang/iex/mix/configuration/Editor.java
src/org/elixir_lang/mix/configuration/Editor.java

Fixes #2703
* Don't restrict Run Configurations to Run in Modules to Elixir modules.
The docs for `ModuleType` say the concept is meant to be deprecated, so don't enforce it and trying to load `ElixirModuleType` in RubyMine breaks as it tries to load `ElixirModuleBuilder` and therefore `JavaModuleBuilder`, which only works in IntelliJ.

Don't restrict Run Configurations to Run in Modules to Elixir modules

---

CHANGELOG.md
gen/org/elixir_lang/psi/stub/call/Deserialized.java
resources/META-INF/changelog.html

Fixes #2698
Fixes #2716
* Increase `SUSPECT_NAME_SET_SIZE` to `20`.
Increased to cover the `15` `impl`s of `String.Chars` in the `geo` hex package.

Increase SUSPECT_NAME_SET_SIZE to 20

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/formatter/MixFormatExternalFormatProcessor.kt

Fixes #2718
* Log if `erl` binary is not found when trying to run `mix format`.
Log instead of letting it throw up the stack and cause an error report since the SDK not being set will be very common.

Log if erl binary is not found when trying to run mix format

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/injection/markdown/Injector.kt

Fixes #2798
* Ignore `authors: ...` for documentation when injecting Markdown.

Ignore `authors: ...` for documentation when injecting Markdown

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/QualifiableAliasImpl.kt

Fixes #2799
* Stop `prependQualifiers` when reaching a qualified bracket operation (`Alias.function[key]`).

Stop prepend qualifier when reaching a qualified bracket operation

---

CHANGELOG.md
gen/org/elixir_lang/psi/scope/type/MultiResolve.kt
resources/META-INF/changelog.html

Fixes #2795
* Skip `-1` and other unary operations when resolving types.

Skip -1 and other unary operations when resolving types

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt

* Ignore maps at the root of files when collecting doc comments.

Ignore maps at the root of files when collecting doc comments

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/PsiElementImpl.kt

Fixes #2773
* Return `emptySequence` from `childExpressions` when `PsiElement` has no `firstChild` or `lastChild`.

Return emptySequence from childExpressions when PsiElement has no firstChild or lastChild

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/scope/Type.kt

Fixes #2807
* Don't descend inside struct literal when resolving types.

Don't descend inside struct literal when resolving types

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/injection/markdown/Injector.kt

Fixes #2771
* Ignore injecting Markdown in calls that read the text from a file, such as in `@moduledoc File.read!(Path.join([__DIR__, "..", "README.md"]))`

Ignore injecting Markdown in calls that read the text from a file

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt

Fixes #2833
* Ignore undocument script code at root of files.
* Alias used in qualified call.
* Integers
* Floats
* Tuples

Ignore calls and literals at root of file when collecting doc comments

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/scope/Type.kt

Fixes #2878
* Stop `ancestorTypeSpec` on `QualifiedMultipleAliases`.

Stop ancestorTypeSpec on QualifiedMultipleAliases

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/injection/markdown/Injector.kt

Fixes #2847
* Ignore pipelines for injecting Markdown in doc comments.

Ignore pipelines for injecting Markdown in doc comments

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/Dep.kt

Fixes #2845
* Ignore useless `warn_missing` in `edeliver`'s `distillery` dep.

Ignore useless `warn_missing` in edeliver's distillery dep

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/reference/Callable.kt

Fixes #3004
* Don't look for variable use scope above EEx tags.
If a variable is declared in an EEx tag then it is actually missing its declaration and cannot be resolved, so ignore its usage.

Don't look for variable use scope above EEx tags

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/injection/markdown/Injector.kt

Fixes #2974
* Ignore `request_body` and `responses` for docs.

Ignore request_body and responses for docs

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt

Ignore hexadecimal numbers at the root of the file when collecting doc comment

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/call/CallImpl.kt
tests/org/elixir_lang/psi/operation/PrefixTest.java

Return an empty array of primaryArguments instead of array with null operand for unary operation without operand

---

CHANGELOG.md
build.gradle
resources/META-INF/changelog.html

Fixes #2960
* Set `sinceBuild` to IntelliJ IDEA 2022.3.
Fixes incorrect compatibility listed with < 2022.3 when < 2022.3 support was removed in 14.0.0 with #2946.

Set sinceBuild to IntelliJ IDEA 2022.3

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/reference/Resolver.kt

Fixes #2956
* Use `minByOrNull` to protect from empty module list.
This fix may not work as the line number reported in the errors is actually outside of the file. This is only a guess that `minBy` was what was throwing the `NoSuchElement` exception.

Use minByOrNull to protect from empty module list

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/call/CallImpl.kt

Fixes #2725
* Ignore `null` operands for `not in` `primaryArguments()`.
Instead of including both left and right operand always and so having null operand in fixed size array return array with only non-null operands.

Ignore `null` operands for `not in` `primaryArguments()`

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/new_project_wizard/Step.kt

Fixes #2747
* Don't allow Elixir SDK without Erlang SDK to be selected for New Project.
The SDK has to be able to work for `mix new`.

Don't allow Elixir SDK without Erlang SDK to be selected for New Project

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt

Ignore strings, charlists, and sigils at the top of file when looking for doc comments

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/ElixirDocumentationProvider.kt

Ignore top-level Aliases when collecting docs

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/injection/markdown/Injector.kt
src/org/elixir_lang/psi/impl/PsiElementImpl.kt

* Ignored `unquote` calls when injecting docs.
* FInd enclosing `quote` when `def`s are inside an `fn` as in Phoenix Route Helpers.

Find enclosing quote when defs are inside of an fn

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/impl/PsiNamedElementImpl.kt

…stead
Fixes #2094
Fixes #2917
* Setting name on a call definition clause sets the name on the head instead.
The JetBrains API both renames the usage references AND the original element where the rename refactoring was started, but when started on a call definition clause the `functionNameElement` is the `def`, `defp`, `defmacro`, or `defmacrop` and so both the name of the call was changed, but the `def*` was also changed to the new name.  Now, if `setName` is called on a definition, the head is renamed instead.

Setting name on a call definition clause sets the name on the head instead

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/dialyzer/service/DialyzerServiceImpl.kt

Fixes #2913
* Check Elixir SDK has Erlang SDK before running dialyzer.
Notify user of configuration error instead of throwin exceptiion when constructing `mix` commandline.

Check Elixir SDK has Erlang SDK before running dialyzer

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/ElementFactory.java
src/org/elixir_lang/psi/impl/PsiNamedElementImpl.kt

* Log if new name element type does not match old name element type.
* Replace name with relative identifier instead of identifier for qualified calls on rename.

Replace name with relative identifier instead of identifier for qualified calls on rename

---

CHANGELOG.md
gen/org/elixir_lang/psi/scope/call_definition_clause/Variants.kt
resources/META-INF/changelog.html
src/org/elixir_lang/psi/scope/CallDefinitionClause.kt
testData/org/elixir_lang/reference/callable/issue_2751/inside_if.ex
testData/org/elixir_lang/reference/callable/issue_2751/outside_if.ex
tests/org/elixir_lang/reference/callable/Issue2751Test.kt

Fixes #2751
* Keep looking for variants above if and unless 
`if` and `unless` used to call `keepProcessing()` after checking if the child calls when resolving or searching for variants, but Variants returned `false` always from `keepProcesssing()`.
This stops the variant search from terminating inside of an `if` or `unless` when it wouldn't outside of one as was reported in https://github.com/KronicDeth/intellij-elixir/issues/2751.
* List `Kernel` and `Kernel.SpecialForms` variants inside modulars.
Keep processing at end of modulars when looking for variants, which will check the implicit imports of `Kernel` and `Kernel.SpecialForms`.
* Prevent listing variants from outer module in nested module

Keep looking for variants above terminal resolution constructs

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/new_project_wizard/Step.kt

* Fix reporting `mix new` errors as notifications
* Don't associate mix new errors with new project as it doesn't have a frame, so the notification was suppressed before.
* Strip color codes from mix new error notification.
* Validate `--app` is set correctly for new projects
* If inferred from project name, make sure the name is valid application name the same as `mix new` does.
* If `--app` is set explicitly, make sure it follows naming rules for `mix new`.

Validate `--app` is set correctly for new projects

---

CHANGELOG.md
build.gradle
gradle.properties
resources/META-INF/changelog.html

Latest build for RubyMine 2023.1 is 231.8109.174
https://www.jetbrains.com/ruby/download/other.html

Update since build for RubyMine and WebStorm

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/new_project_wizard/Step.kt

Until it can be determined how to exit the `setupProject` step cleanly, make the error reporting better for better pre-validation.
Fixes #3238

Include mix new stderr in IOException for better triage

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/psi/scope/Type.kt

Skip bare Aliases when resolving Types

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/mix/Project.kt

Fixes #3174
If the `.elixir_ls` directory is included the `.beam` it produces can interfere with normal `StubIndex` creation.

Exclude .elixir_ls directory when configuring new Projects

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/new_project_wizard/Step.kt

Check if Internal Erlang SDK home path exists for SDK for New Project

---

.github/workflows/test.yml
CHANGELOG.md
build.gradle
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/mix/project/_import/step/ElixirSdkForModuleStep.kt

2023.2 (232 version) was released last week, and it doesn't support the current plugin version.
Fixes https://github.com/KronicDeth/intellij-elixir/issues/3325.
Fixes https://github.com/KronicDeth/intellij-elixir/issues/3326.

Enable 232 version

---

CHANGELOG.md
resources/META-INF/changelog.html
resources/META-INF/plugin.xml

* Add `displayName` in `plugin.xml` for configurables for faster menu loading.
* `org.elixir_lang.facet.configurable.Project` - "Elixir"
* `org.elixir_lang.facets.sdks.erlang.Configurable` - "Internal Erlang SDKs"
* `org.elixir_lang.facets.sdks.elixir.Configurable` - "SDKs"

Add displayName in plugin.xml for configurables for faster menu loading

---

.github/workflows/test.yml
CHANGELOG.md
build.gradle
jps-builder/src/org/elixir_lang/jps/builder/GeneralCommandLine.java
resources/META-INF/changelog.html
src/org/elixir_lang/Process.java
src/org/elixir_lang/formatter/Block.java
src/org/elixir_lang/mix/runner/Status.java
src/org/elixir_lang/reference/resolver/atom/Resolvable.java
src/org/elixir_lang/structure_view/sorter/Time.java
tests/org/elixir_lang/intellij_elixir/Quoter.kt

* Drop support for 2023.2 IDEs.

Fix build for 2023.3

---

CHANGELOG.md
gradle.properties
resources/META-INF/changelog.html
src/org/elixir_lang/documentation/MarkdownFlavourDescriptor.kt

I recently started using Elixir and noticed that code snippets would not be rendered in the documentation. This turned out to be due to missing else branches when rendering links in code snippets. Since the documentation of standard library functions makes heavy use of code to refer to parameters and other things, this will be a great improvement to my Elixir journey.

Render code snippets that are not links

---

CHANGELOG.md
resources/META-INF/changelog.html
src/org/elixir_lang/IEx.kt

Add the correct ERL and elixir arguments for starting IEx depending on the version of elixir sdk

---

jps-builder/tests/org/elixir_lang/jps/BuilderTest.java

Currently, the `ERLANG_SDK_HOME` and `OTP_RELEASE` environment variables need to be set manually when developing and are set in [CI](https://github.com/KronicDeth/intellij-elixir/blob/main/.github/workflows/test.yml#L24).
Example of current setup:
```sh
export ERLANG_SDK_HOME="/home/user/.local/share/mise/installs/erlang/24.3.4.6"
export OTP_VERSION="24.3.4.6"
```
This then breaks when running `gradle test` without these.
This PR implements a quick approach to determine the Erlang SDK home and OTP release version:
1. It first checks for the `ERLANG_SDK_HOME` and `OTP_RELEASE` environment variables.
2. If these are not set, it attempts to infer the values using the `erl` command, which is likely already in the user's PATH.
This change provides a quick and pragmatic fix to improve the …

Use erl to retrieve OTP_RELEASE & ERLANG_SDK_HOME if no environment variable is set when testing

---

build.gradle
gradle.properties

RubyMine/PyCharm/WebStorm are on 2024.2, but IC/IU is on 2024.2.0.1.

Define IDE versions in the gradle.properties

---

resources/META-INF/plugin.xml

This PR is is to introduce reporting errors via [JetBrains Exception Analyzer](https://plugins.jetbrains.com/docs/marketplace/exception-analyzer.html#what-metadata-is-sent).
This allows users to submit errors/exceptions by clicking on the red report icon when an exception occurs - previously this was handled by submitting errors to GitHub as issues.
**This process is entirely opt-in, and exceptions/stacktraces must be submitted manually by the user. This will always be the case, where anything you submit will be opt-in - privacy is the primary concern for anything related to error reporting.**
This process is now handled via JetBrains, all data is sent to them. Stacktraces contain plugin specific errors, and should not contain your code. You can verify this when submitting - you'll see …

Support JetBrains Exception Analyzer

---

build.gradle
gradle.properties

When running an IDE via `./gradlew runIntelliJCommunity` etc, IdeaVim is installed to help test the vim integration.
This does a bump the latest version.
This also bumps to 2.0.1 for the intellij gradle plugin.

Bump intellij platform gradle to 2.0.1 and IdeaVIM to 2.16.0

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

https://youtrack.jetbrains.com/articles/IDEA-A-2100662289/IntelliJ-IDEA-2024.3-243.21565.193-build-Release-Notes

Support Jetbrains 2024.3 (243.21565.193)
